### ISSUE TITLE
FCM : FATAL EXCEPTION: Firebase-WrappedFirebaseMessagingService

### ISSUE THREAD

**Issue by tarek13** [firebase/quickstart-android#1064]
I get this error when i receive notification the app is crash and get this error
my device in android oreo

```
FATAL EXCEPTION: Firebase-WrappedFirebaseMessagingService
    Process: com.vedetta, PID: 15692
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.content.Context.getSystemService(java.lang.String)' on a null object reference
        at android.content.ContextWrapper.getSystemService(ContextWrapper.java:714)
        at com.google.firebase.messaging.zzd.zza(com.google.firebase:firebase-messaging@@20.1.0:10)
        at com.google.firebase.messaging.FirebaseMessagingService.zzc(com.google.firebase:firebase-messaging@@20.1.0:69)
        at com.google.firebase.messaging.zze.run(com.google.firebase:firebase-messaging@@20.1.0:2)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source:6)
        at java.lang.Thread.run(Thread.java:764)
```

**Comment by samtstern** [comment]
@tarek13 this is not enough information to debug the issue.  We need:

- Steps to reproduce (using this quickstart)
- The code that causes this issue
- Information on the device you're using, etc

If you can provide all of that please open a new issue.
