### ISSUE TITLE
Crash by Service not registered: com.google.android.gms.common.internal.zzf@a87a29b android.app.LoadedApk.forgetServiceDispatcher

### ISSUE THREAD

**Issue by jecksonwang** [firebase/quickstart-android#1081]
### Step 1: Describe your environment

  * Android device: Xiaomi MI 8 UD (equuleus)
  * Android OS version: 9.0
  * Google Play Services version: 17.0.0
  * Firebase/Play Services SDK version: 17.0.0
  
### Step 2: Describe the problem:

    app crash by the issue

#### Steps to reproduce:

Appears randomly and randomly during the process of using APP
  
#### Observed Results:

java.lang.IllegalArgumentException: 
  at android.app.LoadedApk.forgetServiceDispatcher (LoadedApk.java:1570)
  at android.app.ContextImpl.unbindService (ContextImpl.java:1702)
  at android.content.ContextWrapper.unbindService (ContextWrapper.java:727)
  at com.google.android.gms.common.stats.ConnectionTracker.unbindService (Unknown Source:25)
  at com.google.android.gms.common.internal.zzf.zzf (Unknown Source:41)
  at com.google.android.gms.common.internal.zze.handleMessage (Unknown Source:45)
  at android.os.Handler.dispatchMessage (Handler.java:102)
  at com.google.android.gms.internal.common.zze.dispatchMessage (Unknown Source:8)
  at android.os.Looper.loop (Looper.java:201)
  at android.app.ActivityThread.main (ActivityThread.java:6806)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:547)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:873)
  
#### Expected Results:

  no carsh
  
#### Relevant Code:

After integrating firebase in my project, I occasionally get the following error

Fatal Exception: java.lang.IllegalArgumentException: Service not registered: com.google.android.gms.common.internal.zzf@a87a29b
   at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1680)
   at android.app.ContextImpl.unbindService(ContextImpl.java:1781)
   at android.content.ContextWrapper.unbindService(ContextWrapper.java:730)
   at com.google.android.gms.common.stats.ConnectionTracker.unbindService(:25)
   at com.google.android.gms.common.internal.zzf.zzf(:41)
   at com.google.android.gms.common.internal.zze.handleMessage(:45)
   at android.os.Handler.dispatchMessage(Handler.java:102)
   at com.google.android.gms.internal.common.zze.dispatchMessage(:8)
   at android.os.Looper.loop(Looper.java:214)
   at android.app.ActivityThread.main(ActivityThread.java:7127)
   at java.lang.reflect.Method.invoke(Method.java)
   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)

I checked the related source code for zzf

  public final void zzf(String var1) {
    zze.zzb(this.zzec).removeMessages(1, this.zzeb);
    zze.zzd(this.zzec).unbindService(zze.zzc(this.zzec), this);
    this.zzea = false;
    this.mState = 2;
}

I would like to ask whether this service is bound by firebase, and when was it unbundled, why did this problem occur when unbundling?

**Comment by hysheng** [comment]
我也遇到同样的问题，请问你解决了吗？

**Comment by samtstern** [comment]
@jecksonwang that class is involved in the connection between your app and Google Play services.  It's not clear from the stack trace how Firebase is involved here.  Do you have any information on how to reproduce this issue?

**Comment by LambdaXiao** [comment]
我也遇到同样的问题，请问你解决了吗？

**Comment by Lans** [comment]
it happened on xiaomi
