### ISSUE TITLE
Cannot copy between TensorflowLite tensor with shape [1, 10, 4] and a Java object with shape [1, 7]

### ISSUE THREAD

**Issue by Jack-Hewson** [firebase/quickstart-android#1091]
### Step 1: Describe your environment

  * Android device: Samsung s10 5G
  * Android OS version: _____
  * Google Play Services version: _____
  * Firebase/Play Services SDK version: _____
  
### Step 2: Describe the problem:
My custom model has an error where the output is [1 10 4] however the program expects it to be only 2 values and not 3

#### Steps to reproduce:

  1. Run the custom model classifier with my model
  
#### Observed Results:

    Caused by: java.lang.IllegalArgumentException: Cannot copy between a TensorFlowLite tensor with shape [1, 10, 4] and a Java object with shape [1, 7].
        at org.tensorflow.lite.Tensor.throwExceptionIfTypeIsIncompatible(Tensor.java:242)
        at org.tensorflow.lite.Tensor.copyTo(Tensor.java:116)
        at org.tensorflow.lite.NativeInterpreterWrapper.run(NativeInterpreterWrapper.java:157)
        at org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(Interpreter.java:250)
        at com.google.android.gms.internal.firebase_ml.zzqw.runForMultipleInputsOutputs(com.google.firebase:firebase-ml-model-interpreter@@22.0.1:4)
        at com.google.android.gms.internal.firebase_ml.zzqo.zza(com.google.firebase:firebase-ml-model-interpreter@@22.0.1:85)
        at com.google.android.gms.internal.firebase_ml.zzqo.zza(com.google.firebase:firebase-ml-model-interpreter@@22.0.1:147)
        at com.google.android.gms.internal.firebase_ml.zzpj.zza(com.google.firebase:firebase-ml-common@@22.0.1:31)
        at com.google.android.gms.internal.firebase_ml.zzpl.call(Unknown Source:8)
        at com.google.android.gms.internal.firebase_ml.zzpf.zza(com.google.firebase:firebase-ml-common@@22.0.1:32)
    	... 6 more
  
#### Expected Results:

Model infered
  
#### Relevant Code:

  ```
  // TODO(you): code here to reproduce the problem
  ```

**Comment by morganchen12** [comment]
Looks like the input is the wrong shape. Where is the input Java object coming from?

**Comment by Jack-Hewson** [comment]
@morganchen12 the java object is 

        int[] outputDims = {1, labelList.size()};

Where the labellist contains the 7 possible labels

        dataOptions =
                new FirebaseModelInputOutputOptions.Builder()
                        .setInputFormat(0, dataType, inputDims)
                        .setOutputFormat(0, dataType, outputDims)
                        .build();

**Comment by morganchen12** [comment]
If you're matching an input to a set of labels, you usually don't have to copy the labels into the TFLite model's inputs. For example, see this [TFLite image recognition example](https://github.com/tensorflow/examples/blob/master/lite/examples/image_classification/android/app/src/main/java/org/tensorflow/lite/examples/classification/tflite/Classifier.java#L218-L230): it uses a single input in the shape of an image, and then the output is an integer which is used to index into an array of labels.

What object are you trying to match to the set of labels?
