### ISSUE TITLE
LiveObjectDetection not working

### ISSUE THREAD

**Issue by yasiralijaved** [firebase/quickstart-android#1160]
### Step 1: Describe your environment

  * Android device: Android Emulator
  * Android OS version: 10
  * Google Play Services version: 12451000
  
### Step 2: Describe the problem:

I get the following a lifecycle and observer related error in console/logcat while launching the LiveObjectDetection Activity. In result the Object detection is not working.

#### Steps to reproduce:

  1. Merge Barcode detection related code into LiveObjectDetection Activity
  2. Delete all un-used resources and classes
  3. run the app and launch the LiveObjectDetection Activity
  4. You will see the mentioned error in logcat and console of debug view
  
#### Observed Results:

* Logcat outout
Error preloading model resource
    com.google.mlkit.common.MlKitException: Internal error has occurred when executing ML Kit tasks
        at com.google.mlkit.common.sdkinternal.ModelResource.zza(com.google.mlkit:common@@16.1.0:32)
        at com.google.mlkit.common.sdkinternal.zzl.run(Unknown Source:10)
        at com.google.mlkit.common.sdkinternal.zzp.run(com.google.mlkit:common@@16.1.0:3)
        at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zzd(com.google.mlkit:common@@16.1.0:24)
        at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zza(com.google.mlkit:common@@16.1.0:30)
        at com.google.mlkit.common.sdkinternal.zzh.run(Unknown Source:2)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.lang.IllegalStateException: Method addObserver must be called on the main thread
        at androidx.lifecycle.LifecycleRegistry.enforceMainThreadIfNeeded(LifecycleRegistry.java:317)
        at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.java:172)
        at com.google.android.libraries.intelligence.acceleration.ProcessStateObserver.zza(com.google.mlkit:vision-internal-vkp@@17.0.0:10)
        at com.google.mlkit.vision.vkp.PipelineManager.start(com.google.mlkit:vision-internal-vkp@@17.0.0:128)
        at com.google.mlkit.vision.objects.defaults.internal.zzd.load(com.google.mlkit:object-detection@@16.2.0:74)
        at com.google.mlkit.common.sdkinternal.ModelResource.zza(com.google.mlkit:common@@16.1.0:24)
        at com.google.mlkit.common.sdkinternal.zzl.run(Unknown Source:10) 
        at com.google.mlkit.common.sdkinternal.zzp.run(com.google.mlkit:common@@16.1.0:3) 
        at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zzd(com.google.mlkit:common@@16.1.0:24) 
        at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zza(com.google.mlkit:common@@16.1.0:30) 
        at com.google.mlkit.common.sdkinternal.zzh.run(Unknown Source:2) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919)

**Comment by samtstern** [comment]
@yasiralijaved the best place to file MLKit issues is now here, that's where the MLKit team is watching:
https://github.com/googlesamples/mlkit

I can't transfer this issue automatically since GitHub doesn't allow cross-organization transfers.

**Comment by yasiralijaved** [comment]
@samtstern thanks. The issue has been moved to the suggested place.
