### ISSUE TITLE
Firebase Storage: Unknown method 'PATCH'; must be one of [OPTIONS, GET, HEAD, POST, PUT, DELETE, TRACE]

### ISSUE THREAD

**Issue by myflashlab** [firebase/quickstart-android#118]
when calling the [updateMetadata](https://firebase.google.com/docs/reference/android/com/google/firebase/storage/StorageReference.html#updateMetadata(com.google.firebase.storage.StorageMetadata)) on ice cream sandwich Android V4.0.3 (in forums I heard that kitkat also has a similar problem), it throws the following error message.

It works fine on lollipop and marshmallow though as we tested.

We did try to add "httpclient-4.5.2.jar" as a dependency in hope of fixing the issue but it didn't work. So, I hope you guys can fix this in the coming release.

```
NetworkRequest: error sending network request PATCH https://firebasestorage.googleapis.com/v0/b/tyu-jhytrf.appspot.com/o/folder%2Fimage.png
        java.net.ProtocolException: Unknown method 'PATCH'; must be one of [OPTIONS, GET, HEAD, POST, PUT, DELETE, TRACE]
        at java.net.HttpURLConnection.setRequestMethod(HttpURLConnection.java:665)
        at libcore.net.http.HttpsURLConnectionImpl.setRequestMethod(HttpsURLConnectionImpl.java:143)
        at bzr.b(:com.google.android.gms.DynamiteModulesC:244)
        at bzr.a(:com.google.android.gms.DynamiteModulesC:270)
        at bzl.onTransact(:com.google.android.gms.DynamiteModulesC:53)
        at android.os.Binder.transact(Binder.java:297)
        at com.google.android.gms.internal.zzamg$zza$zza.zztj(Unknown Source)
        at com.google.android.gms.internal.zzamj.zza(Unknown Source)
        at com.google.android.gms.internal.zzama.zza(Unknown Source)
        at com.google.android.gms.internal.zzama.zzd(Unknown Source)
        at com.google.firebase.storage.zzf.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
        at java.lang.Thread.run(Thread.java:856)
```

**Comment by samtstern** [comment]
@myflashlab thanks for the report, this is very interesting.  Let me look into this/

**Comment by samtstern** [comment]
Since we are tracking this internally and it's not something to do with the quickstart itself, I will mark this as closed.

I'll come back and comment when you can expect to see the fix in production.
