### ISSUE TITLE
Firebase causing Crashes on several devices after instaling from playstore (SQLiteConnection.java )

### ISSUE THREAD

**Issue by bugthug404** [firebase/quickstart-android#1325]
### Step 1: Describe your environment

  * Android device: All Android devices
  * Android OS version: All OS Version
  * Google Play Services version: any
  * Firebase/Play Services SDK version: Latest 18-07-2021
  
### Step 2: Describe the problem:
Firebase Firestore causing crashes to app after downloading from playstore
#### Steps to reproduce:

  1. Its occuring around 30% of the devices according to the crashlytics report

  
#### Observed Results:

Stack Trace Data From Crashlytics

SQLiteConnection.java
android.database.sqlite.SQLiteConnection.nativeExecute

Fatal Exception: java.lang.RuntimeException: Internal error in Cloud Firestore (23.0.3).
       at com.google.firebase.firestore.util.AsyncQueue.lambda$panic$3(AsyncQueue.java:19)
       at com.google.firebase.firestore.util.-$$Lambda$AsyncQueue$jx84dqgUsF4ojecSMurRqFLFD1Y.run(-.java:2)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:7948)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)

Caused by java.lang.RuntimeException: android.database.sqlite.SQLiteDatabaseLockedException: database is locked (code 5 SQLITE_BUSY[5])
       at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor.lambda$executeAndReportResult$1(AsyncQueue.java:14)
       at com.google.firebase.firestore.util.-$$Lambda$AsyncQueue$SynchronizedShutdownAwareExecutor$pKSAgg-ozJ8RbUveSl-44aUfFQw.run(-.java:4)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor$DelayedStartFactory.run(AsyncQueue.java:15)
       at java.lang.Thread.run(Thread.java:919)

Caused by android.database.sqlite.SQLiteDatabaseLockedException: database is locked (code 5 SQLITE_BUSY[5])
       at android.database.sqlite.SQLiteConnection.nativeExecute(SQLiteConnection.java)
       at android.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:867)
       at android.database.sqlite.SQLiteSession.beginTransactionUnchecked(SQLiteSession.java:325)
       at android.database.sqlite.SQLiteSession.beginTransaction(SQLiteSession.java:300)
       at android.database.sqlite.SQLiteDatabase.beginTransaction(SQLiteDatabase.java:766)
       at android.database.sqlite.SQLiteDatabase.beginTransactionWithListener(SQLiteDatabase.java:729)
       at com.google.firebase.firestore.local.SQLitePersistence.runTransaction(SQLitePersistence.java:17)
       at com.google.firebase.firestore.local.LocalStore.startMutationQueue(LocalStore.java:9)
       at com.google.firebase.firestore.local.LocalStore.start(LocalStore.java)
       at com.google.firebase.firestore.core.ComponentProvider.initialize(ComponentProvider.java:41)
       at com.google.firebase.firestore.core.FirestoreClient.initialize(FirestoreClient.java:65)
       at com.google.firebase.firestore.core.FirestoreClient.lambda$new$0(FirestoreClient.java:10)
       at com.google.firebase.firestore.core.FirestoreClient.lambda$new$0$FirestoreClient(FirestoreClient.java)
       at com.google.firebase.firestore.core.-$$Lambda$FirestoreClient$Eq-cAcb1C1mM4tyiJsLJXZ13tyU.run(-.java:8)
       at com.google.firebase.firestore.util.AsyncQueue.lambda$enqueue$2(AsyncQueue.java)
       at com.google.firebase.firestore.util.-$$Lambda$AsyncQueue$Y9GO7zO2DX6MzQJ5TbKtKW_NzO0.call(-.java:2)
       at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor.lambda$executeAndReportResult$1(AsyncQueue.java)
       at com.google.firebase.firestore.util.-$$Lambda$AsyncQueue$SynchronizedShutdownAwareExecutor$pKSAgg-ozJ8RbUveSl-44aUfFQw.run(-.java:4)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor$DelayedStartFactory.run(AsyncQueue.java:15)
       at java.lang.Thread.run(Thread.java:919)

ScionFrontendApi
       at sun.misc.Unsafe.park(Unsafe.java)
       at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:230)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2109)
       at java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:467)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1091)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:919)

pool-20-thread-45
       at sun.misc.Unsafe.park(Unsafe.java)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:190)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:868)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1023)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1334)
       at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:232)
       at com.google.android.gms.tasks.Tasks$zza.await(Tasks.java:2)
       at com.google.android.gms.tasks.Tasks.await(Tasks.java:28)
       at io.flutter.plugins.firebase.core.FlutterFirebasePluginRegistry.lambda$didReinitializeFirebaseCore$1(FlutterFirebasePluginRegistry.java:32)
       at io.flutter.plugins.firebase.core.-$$Lambda$FlutterFirebasePluginRegistry$ciVYnzQeFhYt167J9Kbi6PIvDeA.call(-.java)
       at com.google.android.gms.tasks.zzv.run(zzv.java:4)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:919)

GoogleApiHandler
       at com.android.org.conscrypt.NativeCrypto.SSL_read(NativeCrypto.java)
       at com.android.org.conscrypt.NativeSsl.read(NativeSsl.java:411)
       at com.android.org.conscrypt.ConscryptFileDescriptorSocket$SSLInputStream.read(ConscryptFileDescriptorSocket.java:583)
       at com.android.okhttp.okio.Okio$2.read(Okio.java:145)
       at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:213)
       at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:317)
       at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:311)
       at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:207)
       at com.android.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:388)
       at com.android.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:146)
       at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:900)
       at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:772)
       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:493)
       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:429)
       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:560)
       at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:106)
       at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:30)
       at com.google.android.gms.internal.firebase-auth-api.zzvb.zza(zzvb.java:63)
       at com.google.android.gms.internal.firebase-auth-api.zzul.zzf(zzul.java:20)
       at com.google.android.gms.internal.firebase-auth-api.zzpt.zzp(zzpt.java:18)
       at com.google.android.gms.internal.firebase-auth-api.zztp.zzk(zztp.java:26)
       at com.google.android.gms.internal.firebase-auth-api.zzqr.zzd(zzqr.java:15)
       at com.google.android.gms.internal.firebase-auth-api.zzqq.accept(zzqq.java:6)
       at com.google.android.gms.common.api.internal.zacj.doExecute(zacj.java:6)
       at com.google.android.gms.common.api.internal.zaf.zac(zaf.java:8)
       at com.google.android.gms.common.api.internal.GoogleApiManager$zaa.zac(GoogleApiManager.java:9)
       at com.google.android.gms.common.api.internal.GoogleApiManager$zaa.zab(GoogleApiManager.java:22)
       at com.google.android.gms.common.api.internal.GoogleApiManager$zaa.zaa(GoogleApiManager.java:17)
       at com.google.android.gms.common.api.internal.GoogleApiManager.handleMessage(GoogleApiManager.java:534)
       at android.os.Handler.dispatchMessage(Handler.java:103)
       at com.google.android.gms.internal.base.zar.dispatchMessage(zar.java)
       at android.os.Looper.loop(Looper.java:237)
       at android.os.HandlerThread.run(HandlerThread.java:67)

There are 84 threads like this in total i've not posted all of them
#### Expected Results:

No Crashes
  
#### Relevant Code:

  ```
 Dependencies Used in Project

dependencies:
  flutter:
    sdk: flutter
  bloc: ^7.0.0
  cloud_firestore: ^2.4.0
  cupertino_icons: ^1.0.3
  dio: ^4.0.0
  file_picker: ^3.0.3
  firebase_auth: ^3.0.1
  firebase_core: ^1.4.0
  flutter_bloc: ^7.0.0
  font_awesome_flutter: ^9.1.0
  google_fonts: ^2.1.0
  image_picker: ^0.8.2
  intl: ^0.17.0
  path_provider: ^2.0.2
  permission_handler: ^8.1.4+1
  shared_preferences: ^2.0.6
  uuid: ^3.0.4
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  firebase_messaging: ^10.0.4
  bubble_bottom_bar: ^1.2.0
  url_launcher: ^6.0.9
  page_transition: ^2.0.2
  fbroadcast: ^1.1.1
  chewie: ^1.2.2
  video_player: ^2.1.12
  open_file: ^3.2.1
  awesome_notifications: ^0.0.6+10
  flutter_linkify: ^5.0.2
  linkable: ^2.0.0
  firebase_crashlytics: ^2.1.1
  light_compressor: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^1.1.8+4
  flutter_launcher_icons: ^0.9.0
  change_app_package_name: ^1.0.0

  ```

**Comment by tlworkssoftware** [comment]
I'm going through the same problem, did you have any solution?

**Comment by thatfiredev** [comment]
@bugthug404 It looks like you're using Flutter and this repository has Android samples only.
Your bug has already been reported on https://github.com/firebase/flutterfire/issues/6087
I suggest you follow that thread. I'll close this for now.
