### ISSUE TITLE
[invites] App crashes when pressing the "Preview email" button

### ISSUE THREAD

**Issue by zawasp** [firebase/quickstart-android#137]
While testing app invites, I always get a crash when pressing the "Preview email" button.
### Step 2: Describe your environment
- Android device: Nexus 6P
- Android OS version: 7.0
- Google Play Services version: 9.4.0
- Firebase/Play Services SDK version: 9.4.0
### Step 3: Describe the problem:

This happens since I integrated AdscendMedia Android ads SDK. It seems Firebase PreviewActivity tries to inflate `com.adscendmedia.sdk.ui.OptionSectionView` instead of its own internal class.
#### Observed Results:

Logcat output:

```
''09-18 16:36:13.079 29324-29324/com.planarbox.money.tree E/UncaughtException: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.planarbox.money.tree/com.google.android.gms.appinvite.PreviewActivity}: android.view.InflateException: Binary XML file line #2: Error inflating class com.adscendmedia.sdk.ui.OptionSectionView
                                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2411)
                                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2474)
                                                                                 at android.app.ActivityThread.access$800(ActivityThread.java:144)
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1359)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                 at android.os.Looper.loop(Looper.java:155)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5696)
                                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                                 at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1028)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
                                                                              Caused by: android.view.InflateException: Binary XML file line #2: Error inflating class com.adscendmedia.sdk.ui.OptionSectionView
                                                                                 at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:757)
                                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:482)
                                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
                                                                                 at com.google.android.gms.appinvite.PreviewActivity.zza(Unknown Source)
                                                                                 at com.google.android.gms.appinvite.PreviewActivity.onCreate(Unknown Source)
                                                                                 at android.app.Activity.performCreate(Activity.java:5958)
                                                                                 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1129)
                                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2364)
                                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2474) 
                                                                                 at android.app.ActivityThread.access$800(ActivityThread.java:144) 
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1359) 
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                 at android.os.Looper.loop(Looper.java:155) 
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5696) 
                                                                                 at java.lang.reflect.Method.invoke(Native Method) 
                                                                                 at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1028) 
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823) 
                                                                              Caused by: java.lang.ClassNotFoundException: Didn't find class "com.adscendmedia.sdk.ui.OptionSectionView" on path: DexPathList[[directory "."],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
                                                                                 at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                                 at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                                 at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                                 at android.view.LayoutInflater.createView(LayoutInflater.java:571)
                                                                                 at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
                                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:482) 
                                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:414) 
                                                                                 at com.google.android.gms.appinvite.PreviewActivity.zza(Unknown Source) 
                                                                                 at com.google.android.gms.appinvite.PreviewActivity.onCreate(Unknown Source) 
                                                                                 at android.app.Activity.performCreate(Activity.java:5958) 
                                                                                 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1129) 
                                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2364) 
                                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2474) 
                                                                                 at android.app.ActivityThread.access$800(ActivityThread.java:144) 
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1359) 
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                 at android.os.Looper.loop(Looper.java:155) 
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5696) 
                                                                                 at java.lang.reflect.Method.invoke(Native Method) 
                                                                                 at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1028) 
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823) 
                                                                                Suppressed: java.lang.ClassNotFoundException: com.adscendmedia.sdk.ui.OptionSectionView
                                                                                 at java.lang.Class.classForName(Native Method)
                                                                                 at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                                                 at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                                                 at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                                                        ... 20 more
                                                                              Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
```
#### Expected Results:

  Open the preview email

**Comment by samtstern** [comment]
@zawasp which **Preview Email** button are you talking about?  Is this using the quickstart code in this repo?

**Comment by samtstern** [comment]
@zawasp this bug has been open for ~6 weeks without a response.  I am going to close it as stale, if you're still having this issue please re-open and we can discuss.
