### ISSUE TITLE
Crash due to conflict between com.google.firebase:firebase-perf-ktx:20.0.6 and androidx.health:health-services-client:1.0.0-alpha03

### ISSUE THREAD

**Issue by teddis** [firebase/quickstart-android#1374]
We use androidx.health:health-services-client:1.0.0-alpha03 to obtain heartbeat measurements on Wear OS 3.0 (Samsung Galaxy Watch 4). 

We're seeing the following crash as result of using the library com.google.firebase:firebase-perf-ktx:20.0.6 so we can't using Firebase performance. I've tried testing with earlier releases. Same crash with alpha02. Going further back to alpha01 doesn't include necessary functionality to measure heartbeat. 

Our build targets:

        minSdk 30
        targetSdk 31

Including these in build.gradle:

    implementation platform("com.google.firebase:firebase-bom:29.0.4")
    implementation "com.google.firebase:firebase-analytics-ktx"
    implementation "com.google.firebase:firebase-crashlytics-ktx"
    implementation "com.google.firebase:firebase-perf-ktx:20.0.6"

This appears to be source of the problem, in our code when attempting to register our callback:

    override fun onStart() {
        healthClient.measureClient.registerCallback(
            DataType.HEART_RATE_BPM,
            heartRateCallback
        )
    }

The crash:

2022-05-20 09:29:30.117 23830-23830/com.safeinhome.remotesupport.wear.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.safeinhome.remotesupport.wear.debug, PID: 23830
    java.lang.ClassCastException: androidx.health.services.client.proto.DataProto$DataType$TimeType$TimeTypeVerifier cannot be cast to java.lang.String
        at com.google.protobuf.MessageSchema.newSchemaForRawMessageInfo(MessageSchema.java:507)
        at com.google.protobuf.MessageSchema.newSchema(MessageSchema.java:227)
        at com.google.protobuf.ManifestSchemaFactory.newSchema(ManifestSchemaFactory.java:77)
        at com.google.protobuf.ManifestSchemaFactory.createSchema(ManifestSchemaFactory.java:71)
        at com.google.protobuf.Protobuf.schemaFor(Protobuf.java:90)
        at com.google.protobuf.Protobuf.schemaFor(Protobuf.java:104)
        at com.google.protobuf.GeneratedMessageLite.makeImmutable(GeneratedMessageLite.java:175)
        at com.google.protobuf.GeneratedMessageLite$Builder.buildPartial(GeneratedMessageLite.java:395)
        at com.google.protobuf.GeneratedMessageLite$Builder.build(GeneratedMessageLite.java:403)
        at androidx.health.services.client.data.DataType$proto$2.invoke(DataType.kt:89)
        at androidx.health.services.client.data.DataType$proto$2.invoke(DataType.kt:84)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at androidx.health.services.client.data.DataType.getProto(DataType.kt:84)
        at androidx.health.services.client.data.DataType.getProto(DataType.kt:36)
        at androidx.health.services.client.data.ProtoParcelable$bytes$2.invoke(ProtoParcelable.kt:37)
        at androidx.health.services.client.data.ProtoParcelable$bytes$2.invoke(ProtoParcelable.kt:37)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at androidx.health.services.client.data.ProtoParcelable.getBytes(ProtoParcelable.kt:37)
        at androidx.health.services.client.data.ProtoParcelable.hashCode(ProtoParcelable.kt:61)
        at androidx.health.services.client.impl.MeasureCallbackStub$MeasureCallbackKey.hashCode(Unknown Source:2)
        at java.util.HashMap.hash(HashMap.java:338)
        at java.util.HashMap.get(HashMap.java:556)
        at androidx.health.services.client.impl.MeasureCallbackStub$MeasureCallbackCache.getOrCreate(MeasureCallbackStub.kt:90)
        at androidx.health.services.client.impl.ServiceBackedMeasureClient.registerCallback(ServiceBackedMeasureClient.kt:71)
        at androidx.health.services.client.impl.ServiceBackedMeasureClient.registerCallback(ServiceBackedMeasureClient.kt:63)
        at com.safeinhome.remotesupport.wear.data.repositories.WornRepository.onStart(WornRepository.kt:35)
        at com.safeinhome.remotesupport.wear.data.repositories.BaseSensorRepository.start(BaseSensorRepository.kt:21)
        at com.safeinhome.remotesupport.wear.managers.SensorsManager.start(SensorsManager.kt:61)
        at com.safeinhome.remotesupport.wear.ui.splash.SplashViewModel$1.invokeSuspend(SplashViewModel.kt:28)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7651)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by thatfiredev** [comment]
@teddis Can you confirm the same code runs without crashes once you remove the firebase perfmon dependency?

**Comment by teddis** [comment]
Yes

**Comment by thatfiredev** [comment]
@teddis 
Perfect! I'll check which versions each library uses and see how can they update to matching protobuf versions.
Thanks for the feedback!
