### ISSUE TITLE
android firebase file upload in background service app crashed when I passed uri to the service 

### ISSUE THREAD

**Issue by chAqibjaved** [firebase/quickstart-android#1411]
### Step 1: Describe your environment

  * Android device: _Samsing A50____
  * Android OS version: ___11
  * Google Play Services version: _____
  * Firebase/Play Services SDK version: _____19.6.0
  
#### Steps to reproduce:

  1. first i take picture from camera ang get URI of the picture 
  2. then I call the service to upload image to firebase but app crashs with following error see logcat.
  3. _____
  
#### Observed Results:

  2022-09-26 12:59:08.656 28108-28108/com.punjabtransport.smokeinspection E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.punjabtransport.smokeinspection, PID: 28108
    java.lang.RuntimeException: Unable to start service com.punjabtransport.smokeinspection.service.MyUploadService@4fc0fec with Intent { act=action_upload cmp=com.punjabtransport.smokeinspection/.service.MyUploadService (has extras) }: java.lang.SecurityException: No persistable permission grants found for UID 10882 and Uri content://com.punjabtransport.smokeinspection.provider/external_files/DCIM/PKCP_IMAGE_20220926_125843_1420310713270111115.jpg
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4813)
        at android.app.ActivityThread.access$2000(ActivityThread.java:301)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2215)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8653)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
     Caused by: java.lang.SecurityException: No persistable permission grants found for UID 10882 and Uri content://com.punjabtransport.smokeinspection.provider/external_files/DCIM/PKCP_IMAGE_20220926_125843_1420310713270111115.jpg
        at android.os.Parcel.createExceptionOrNull(Parcel.java:2385)
        at android.os.Parcel.createException(Parcel.java:2369)
        at android.os.Parcel.readException(Parcel.java:2352)
        at android.os.Parcel.readException(Parcel.java:2294)
        at android.app.IUriGrantsManager$Stub$Proxy.takePersistableUriPermission(IUriGrantsManager.java:280)
        at android.content.ContentResolver.takePersistableUriPermission(ContentResolver.java:2861)
        at com.punjabtransport.smokeinspection.service.MyUploadService.onStartCommand(MyUploadService.java:68)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4795)
        at android.app.ActivityThread.access$2000(ActivityThread.java:301) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2215) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:246) 
        at android.app.ActivityThread.main(ActivityThread.java:8653) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130) 
     Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.uri.UriGrantsManagerService.takePersistableUriPermission(UriGrantsManagerService.java:367)
        at android.app.IUriGrantsManager$Stub.onTransact(IUriGrantsManager.java:139)
        at android.os.Binder.execTransactInternal(Binder.java:1195)
        at android.os.Binder.execTransact(Binder.java:1159)

  
#### Expected Results:

  * What did you expect to happen?
  
#### Relevant Code:

  ```
    startService(new Intent(Newsmokeapplication.this, MyUploadService.class)
                                            .putExtra(MyUploadService.EXTRA_FILE_URI, attachmentsList.get(0).getUri())
                                            .setAction(MyUploadService.ACTION_UPLOAD));
  ```

**Comment by thatfiredev** [comment]
@chAqibjaved this seems to be related to #1431 , which has just been merged.

Can you please pull the changes from our main branch and try again?
