### ISSUE TITLE
Firebase crash in 9.4.0 

### ISSUE THREAD

**Issue by sathishkumars92** [firebase/quickstart-android#147]
Another similar crash:

Device: Batmobile XT320
Android v4.3.1
Rooted
Firebase 9.4.0

Fatal Exception: java.lang.NullPointerException
       at com.google.firebase.messaging.FirebaseMessagingService.zzo(Unknown Source)
       at com.google.firebase.messaging.FirebaseMessagingService.zzn(Unknown Source)
       at com.google.firebase.messaging.FirebaseMessagingService.zzm(Unknown Source)
       at com.google.firebase.iid.zzb$2.run(Unknown Source)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
       at java.lang.Thread.run(Thread.java:841)

**Comment by kroikie** [comment]
This looks like an issue with Google Play services version. What version of Google Play services is installed on the device that you are using?

**Comment by samtstern** [comment]
@sathishkumars92 we see crashes like this with the Batmobile XT320 all the time, but never with any other device type.  I have a few theories on this:

- That device is real and somehow breaks specification with all other Android devices out there (unlikely)
- There is some emulator or non-real device out there posing as the Batmobile XT320 (likely).  If you google "Batmobile XT320 Crash" you will find many people complaining that their libraries crash on this device.

Because of the information above I am going to close this issue as I am pretty sure there is nothing we can do about it (short of figuring out the Batmobile mystery).  If you come across this crash on any other device model please re-open this issue, would love to dig into it more.
