### ISSUE TITLE
firebase bug

### ISSUE THREAD

**Issue by billdizl** [firebase/quickstart-android#1505]
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.firebase.perf.application.FrameMetricsRecorder.start()' on a null object reference
       at com.google.firebase.perf.application.AppStateMonitor.onActivityStarted(AppStateMonitor.java:199)
       at android.app.Application.dispatchActivityStarted(Application.java:420)
       at android.app.Activity.dispatchActivityStarted(Activity.java:1451)
       at android.app.Activity.onStart(Activity.java:1969)
       at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:472)
       at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:246)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1510)
       at android.app.Activity.performStart(Activity.java:8616)
       at android.app.ActivityThread.handleStartActivity(ActivityThread.java:4204)
       at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
       at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2574)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8757)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

**Comment by thatfiredev** [comment]
@billdizl Can you please share the code that is causing this issue?

**Comment by thatfiredev** [comment]
@billdizl Thanks for clarifying.  In that case it seems like this as an issue with the [firebase-android-sdk](https://github.com/firebase/firebase-android-sdk) - I'm transferring it there.
