### ISSUE TITLE
Play intigrity with phone auth verification failed

### ISSUE THREAD

**Issue by rajSapkota26** [firebase/quickstart-android#1580]
Hi, I am getting this error when trying to verify phone number with OTP.

Here is what I did to solve this:

1Added both release and debug SHA 1 && SHA 256 key to Firebase App Settings
2Added SHA 1 && SHA 256 to Google API Key and made that unrestricted
3Registered Play Integrity in FIrebase
4 add SHA1 && SHA 256 in play integrity on app check firebase
com.google.firebase.auth.FirebaseAuthException: This request is missing a valid app identifier, meaning that Play Integrity checks, and reCAPTCHA checks were unsuccessful. Please try again, or check the logcat for more details.
2024-01-23 07:45:49.693 7435-7435 System.err at com.google.android.gms.internal.firebase-auth-api.zzach.zza(com.google.firebase:firebase-auth@@22.3.1:39)
2024-01-23 07:45:49.693 7435-7435 System.err at com.google.android.gms.internal.firebase-auth-api.zzadb.zza(com.google.firebase:firebase-auth@@22.3.1:3)
2024-01-23 07:45:49.693 7435-7435 System.err at com.google.android.gms.internal.firebase-auth-api.zzade.run(com.google.firebase:firebase-auth@@22.3.1:4)
2024-01-23 07:45:49.693 7435-7435 System.err at android.os.Handler.handleCallback(Handler.java:942)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:211)
at android.os.Looper.loop(Looper.java:300)
at android.app.ActivityThread.main(ActivityThread.java:8410)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)

**Comment by ayatk78** [comment]
### [Download Link ](https://pcsoftsfull.org/after-verification-click-go-to-download/)
