### ISSUE TITLE
Fatal Exception: java.lang.SecurityException: !@Too many alarms (500) registered from pid 12771 uid 10408

### ISSUE THREAD

**Issue by RenshawPeng** [firebase/quickstart-android#185]
# Version: 8.23 (823)
# Issue #: 970
# Issue ID: 583171380aeb16625b130fe6
# Session ID: 58364c3900790001181e80cd2d4dc129
# Date: 2016-11-24T02:11:38Z
# OS Version: 6.0.1
# Device: SM-G925I
# RAM Free: 15.4%
# Disk Free: 25.4%

#0. Crashed: pool-24-thread-1: 0 0 0x0000000000000000
       at android.os.Parcel.readException(Parcel.java:1620)
       at android.os.Parcel.readException(Parcel.java:1573)
       at android.app.IAlarmManager$Stub$Proxy.set(IAlarmManager.java:217)
       at android.app.AlarmManager.setImpl(AlarmManager.java:484)
       at android.app.AlarmManager.set(AlarmManager.java:260)
       at com.google.firebase.iid.FirebaseInstanceIdService.zzagc(Unknown Source)
       at com.google.firebase.iid.FirebaseInstanceIdService.zzd(Unknown Source)
       at com.google.firebase.iid.FirebaseInstanceIdService.zza(Unknown Source)
       at com.google.firebase.iid.FirebaseInstanceIdService.zzm(Unknown Source)
       at com.google.firebase.iid.zzb$2.run(Unknown Source)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)

--

Fatal Exception: java.lang.SecurityException: !@Too many alarms (500) registered from pid 12771 uid 10408
       at android.os.Parcel.readException(Parcel.java:1620)
       at android.os.Parcel.readException(Parcel.java:1573)
       at android.app.IAlarmManager$Stub$Proxy.set(IAlarmManager.java:217)
       at android.app.AlarmManager.setImpl(AlarmManager.java:484)
       at android.app.AlarmManager.set(AlarmManager.java:260)
       at com.google.firebase.iid.FirebaseInstanceIdService.zzagc(Unknown Source)
       at com.google.firebase.iid.FirebaseInstanceIdService.zzd(Unknown Source)
       at com.google.firebase.iid.FirebaseInstanceIdService.zza(Unknown Source)
       at com.google.firebase.iid.FirebaseInstanceIdService.zzm(Unknown Source)
       at com.google.firebase.iid.zzb$2.run(Unknown Source)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)

**Comment by flasher297** [comment]
The same issues with com.google.firebase:firebase-messaging:9.6.1 on next devices:

Android: 6.0.1
Android Build: MMB29K.G930FXXU1BPJG
Manufacturer: samsung
Model: SM-G930F

-------------------------

Android: 6.0.1
Android Build: MMB29K.G925FXXU4DPIH
Manufacturer: samsung
Model: SM-G925F

-------------------------

Android: 6.0.1
Android Build: MMB29K.G935FXXU1BPJG
Manufacturer: samsung
Model: SM-G935F

**Comment by RenshawPeng** [comment]
@flasher297  http://stackoverflow.com/questions/40673549/fatal-exception-java-lang-securityexception-too-many-alarms-500-registered

**Comment by samtstern** [comment]
@RenshawPeng what version of the Firebase SDK are you using?  This issue was present in `9.4.0` but should be fixed in the latest version, which is `10.0.0` (it may be fixed in `9.8.0` as well).

**Comment by RenshawPeng** [comment]
@samtstern  Firebase SDK  version 9.8.0

**Comment by RenshawPeng** [comment]
@samtstern

**Comment by RahulSDeshpande** [comment]
Just to update about this issue,
```compile 'com.google.firebase:firebase-messaging:10.0.1'``` wont solve the issue !!
```compile 'com.google.firebase:firebase-core:10.0.1'``` also needs to be added to get rid of the error !!

Please confirm folks :)

Cheers !!

**Comment by chhota89** [comment]
result.getStatus().isSuccess() is previously giving true. And after some time is always giving false. what is problem? any update
