### ISSUE TITLE
Firebase Google Auth Task throwing error

### ISSUE THREAD

**Issue by sandeeptengale** [firebase/quickstart-android#186]
`com.google.firebase.FirebaseException: An internal error has occurred. [ Bad Request ]
                                                                                  at com.google.android.gms.internal.zzbix.zzcb(Unknown Source)
                                                                                  at com.google.android.gms.internal.zzbiu$zzj.zza(Unknown Source)
                                                                                  at com.google.android.gms.internal.zzbjf.zzcc(Unknown Source)
                                                                                  at com.google.android.gms.internal.zzbjf$zza.onFailure(Unknown Source)
                                                                                  at com.google.android.gms.internal.zzbja$zza.onTransact(Unknown Source)
                                                                                  at android.os.Binder.execTransact(Binder.java:446)`

I am trying to do login with Google, but after `onComplete(@NonNull Task<AuthResult> task)` is executed. Task.isSuccessful() always returns false and throws the above exception. I verified SHA1 and google-service.json is also present in my app folder. Please let me know if am missing something

**Comment by gurpreet06000** [comment]
I am trying to do login with Google, but after onComplete(@NonNull Task<AuthResult> task) is executed. Task.isSuccessful() always returns false and throws the above exception. I verified SHA1 and google-service.json is also present in my app folder. Please let me know if am missing something

**Comment by samtstern** [comment]
@sandeeptengale can you provide any more logs from the device besides that error?

**Comment by sandeeptengale** [comment]
@samtstern 

 I/MaliEGL: [Mali]window_type=1, is_framebuffer=0, errnum = 0
 [Mali]surface->num_buffers=4, surface->num_frames=3, win_min_undequeued=1
 I/MaliEGL: [Mali]max_allowed_dequeued_buffers=3
 W/DynamiteModule: Local module descriptor class for com.google.firebase.auth not found.
 I/art: Background sticky concurrent mark sweep GC freed 15511(1138KB) AllocSpace objects, 0(0B) LOS objects, 12% free, 8MB/10MB, paused 13.259ms total 82.840ms
 I/art: Background sticky concurrent mark sweep GC freed 3667(257KB) AllocSpace objects, 0(0B) LOS objects, 3% free, 9MB/10MB, paused 8.317ms total 30.450ms
 I/art: Background sticky concurrent mark sweep GC freed 2824(203KB) AllocSpace objects, 0(0B) LOS objects, 3% free, 9MB/10MB, paused 14.685ms total 39.481ms

Is it because of

'DynamiteModule: Local module descriptor class for com.google.firebase.auth not found.' ??

**Comment by samtstern** [comment]
@sandeeptengale no that's not a problem.  Those logs don't contain much information ... can you describe what you're trying to do?

**Comment by sandeeptengale** [comment]
@samtstern I wanted to know what is that exception saying [Bad Request] and why isSuccessful() return false. I can manage my use case without it. I just need IdToken from this process, which I already got. We can close this if you are not getting anything out of my logs

**Comment by ebukaprof** [comment]
I am getting an error after adding google-service,json and including SHA-1.
com.google.firebase.FirebaseException: An internal error has occurred. [ INVALID_APP_CREDENTIAL:App validation failed ]
                                                                            at com.google.android.gms.internal.jy.zzK(Unknown Source)
                                                                            at com.google.android.gms.internal.ko.zza(Unknown Source)
                                                                            at com.google.android.gms.internal.kp.run(Unknown Source)
                                                                            at android.os.Handler.handleCallback(Handler.java:815)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:104)
                                                                            at android.os.Looper.loop(Looper.java:194)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5637)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at java.lang.reflect.Method.invoke(Method.java:372)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)
