### ISSUE TITLE
Firebase API initialization failure: Caused by: java.lang.IllegalArgumentException: Given String is empty or null

### ISSUE THREAD

**Issue by wangbourne** [firebase/quickstart-android#210]
My configuration: Android 2.2.3
build.gradle in module
1. compile 'com.google.firebase:firebase-auth:10.0.1
2. apply plugin: 'com.google.gms.google-services'

build.gradle in app:
1. classpath 'com.google.gms:google-services:1.5.0

Detailed error message:

`01-18 04:31:58.104 1771-1771/com.FABC.FFC_Android_dev A/FirebaseApp: Firebase API initialization failure.
                                                                               java.lang.reflect.InvocationTargetException
                                                                                   at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                   at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                   at com.google.firebase.FirebaseApp.zza(Unknown Source)
                                                                                   at com.google.firebase.FirebaseApp.initializeApp(Unknown Source)
                                                                                   at com.google.firebase.FirebaseApp.initializeApp(Unknown Source)
                                                                                   at com.google.firebase.FirebaseApp.initializeApp(Unknown Source)
                                                                                   at com.google.firebase.provider.FirebaseInitProvider.onCreate(Unknown Source)
                                                                                   at android.content.ContentProvider.attachInfo(ContentProvider.java:1591)
                                                                                   at android.content.ContentProvider.attachInfo(ContentProvider.java:1562)
                                                                                   at com.google.firebase.provider.FirebaseInitProvider.attachInfo(Unknown Source)
                                                                                   at android.app.ActivityThread.installProvider(ActivityThread.java:4774)
                                                                                   at android.app.ActivityThread.installContentProviders(ActivityThread.java:4369)
                                                                                   at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4309)
                                                                                   at android.app.ActivityThread.access$1500(ActivityThread.java:135)
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                   at android.os.Looper.loop(Looper.java:136)
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5001)
                                                                                   at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                   at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                                                                   at dalvik.system.NativeStart.main(Native Method)
                                                                                Caused by: java.lang.IllegalArgumentException: Given String is empty or null
                                                                                   at com.google.android.gms.common.internal.zzac.zzdv(Unknown Source)
                                                                                   at com.google.android.gms.internal.zzbjc$zza$zza.<init>(Unknown Source)
                                                                                   at com.google.firebase.auth.FirebaseAuth.zzb(Unknown Source)
                                                                                   at com.google.firebase.auth.FirebaseAuth.<init>(Unknown Source)
                                                                                   at com.google.android.gms.internal.zzbkg.<init>(Unknown Source)
                                                                                   at com.google.firebase.auth.FirebaseAuth.zzd(Unknown Source)
                                                                                   at com.google.firebase.auth.FirebaseAuth.zzc(Unknown Source)
                                                                                   at com.google.firebase.auth.FirebaseAuth.getInstance(Unknown Source)
                                                                                   at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                   at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                                   at com.google.firebase.FirebaseApp.zza(Unknown Source) 
                                                                                   at com.google.firebase.FirebaseApp.initializeApp(Unknown Source) 
                                                                                   at com.google.firebase.FirebaseApp.initializeApp(Unknown Source) 
                                                                                   at com.google.firebase.FirebaseApp.initializeApp(Unknown Source) 
                                                                                   at com.google.firebase.provider.FirebaseInitProvider.onCreate(Unknown Source) 
                                                                                   at android.content.ContentProvider.attachInfo(ContentProvider.java:1591) 
                                                                                   at android.content.ContentProvider.attachInfo(ContentProvider.java:1562) 
                                                                                   at com.google.firebase.provider.FirebaseInitProvider.attachInfo(Unknown Source) 
                                                                                   at android.app.ActivityThread.installProvider(ActivityThread.java:4774) 
                                                                                   at android.app.ActivityThread.installContentProviders(ActivityThread.java:4369) 
                                                                                   at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4309) 
                                                                                   at android.app.ActivityThread.access$1500(ActivityThread.java:135) 
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256) 
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                   at android.os.Looper.loop(Looper.java:136) 
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5001) 
                                                                                   at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                   at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785) 
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601) 
                                                                                   at dalvik.system.NativeStart.main(Native Method) 
01-18 04:31:58.108 1771-1771/com.FABC.FFC_Android_dev E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                  Process: com.FABC.FFC_Android_dev, PID: 1771
                                                                                  java.lang.VerifyError: com/google/android/gms/measurement/internal/zzt
                                                                                      at com.google.android.gms.measurement.AppMeasurementContentProvider.onCreate(Unknown Source)
                                                                                      at android.content.ContentProvider.attachInfo(ContentProvider.java:1591)
                                                                                      at android.content.ContentProvider.attachInfo(ContentProvider.java:1562)
                                                                                      at android.app.ActivityThread.installProvider(ActivityThread.java:4774)
                                                                                      at android.app.ActivityThread.installContentProviders(ActivityThread.java:4369)
                                                                                      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4309)
                                                                                      at android.app.ActivityThread.access$1500(ActivityThread.java:135)
                                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                      at android.os.Looper.loop(Looper.java:136)
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:5001)
                                                                                      at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                      at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                                                                      at dalvik.system.NativeStart.main(Native Method)
01-18 04:32:07.852 633-647/system_process E/WindowManager: Starting window AppWindowToken{529a3898 token=Token{52995ed0 ActivityRecord{5299860c u0 com.FABC.FFC_Android_dev/com.FABC.android_ffc.AppStart t3}}} timed out`

**Comment by samtstern** [comment]
@wangbourne  You have `classpath 'com.google.gms:google-services:1.5.0`

I think you want `classpath 'com.google.gms:google-services:3.0.0`

**Comment by wangbourne** [comment]
You are right :)

**Comment by Zapnologica** [comment]
I get the same error with `classpath 'com.google.gms:google-services:3.0.0`

**Comment by alexkendall** [comment]
Same error.

**Comment by nileshkatuwal** [comment]
add this in gradle (worked for me)

compile 'com.google.android.gms:play-services:10.2.1'
