### ISSUE TITLE
I can not run in my application firebasse

### ISSUE THREAD

**Issue by EminDemiri** [firebase/quickstart-android#245]
Android device: Huawei p9plus (vie-l09)
Android OS version: 6.0
Firebase/Play Services SDK version: 10.2.1
  
### Step 3: Describe the problem:
I'm trying to use both Firebase-crash Firebase-analytics but without success.

The error reports I receive it but if I try to create an event I get error, the same for analytics.

In practice, it all works only if I do not create an exception or try to execute a logevent.

I always get this error during application startup:

`03-23 16:42:48.488 14912-14912/? E/FirebaseApp: Firebase API initialization failure.
                                                java.lang.reflect.InvocationTargetException
                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                    at com.google.firebase.FirebaseApp.zza(Unknown Source)
                                                    at com.google.firebase.FirebaseApp.initializeApp(Unknown Source)
                                                    at com.google.firebase.FirebaseApp.initializeApp(Unknown Source)
                                                    at com.google.firebase.FirebaseApp.initializeApp(Unknown Source)
                                                    at com.google.firebase.provider.FirebaseInitProvider.onCreate(Unknown Source)
                                                    at android.content.ContentProvider.attachInfo(ContentProvider.java:1748)
                                                    at android.content.ContentProvider.attachInfo(ContentProvider.java:1723)
                                                    at com.google.firebase.provider.FirebaseInitProvider.attachInfo(Unknown Source)
                                                    at android.app.ActivityThread.installProvider(ActivityThread.java:5366)
                                                    at android.app.ActivityThread.installContentProviders(ActivityThread.java:4887)
                                                    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4818)
                                                    at android.app.ActivityThread.access$1600(ActivityThread.java:168)
                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1440)
                                                    at android.os.Handler.dispatchMessage(Handler.java:102)
                                                    at android.os.Looper.loop(Looper.java:150)
                                                    at android.app.ActivityThread.main(ActivityThread.java:5665)
                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:799)
                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:689)
                                                 Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/internal/zztv;
                                                    at com.google.firebase.crash.internal.config.flag.Flags.<clinit>(Unknown Source)
                                                    at com.google.firebase.crash.internal.config.flag.Flags.initialize(Unknown Source)
                                                    at com.google.firebase.crash.FirebaseCrash.getInstance(Unknown Source)
                                                    at java.lang.reflect.Method.invoke(Native Method) 
                                                    at com.google.firebase.FirebaseApp.zza(Unknown Source) 
                                                    at com.google.firebase.FirebaseApp.initializeApp(Unknown Source) 
                                                    at com.google.firebase.FirebaseApp.initializeApp(Unknown Source) 
                                                    at com.google.firebase.FirebaseApp.initializeApp(Unknown Source) 
                                                    at com.google.firebase.provider.FirebaseInitProvider.onCreate(Unknown Source) 
                                                    at android.content.ContentProvider.attachInfo(ContentProvider.java:1748) 
                                                    at android.content.ContentProvider.attachInfo(ContentProvider.java:1723) 
                                                    at com.google.firebase.provider.FirebaseInitProvider.attachInfo(Unknown Source) 
                                                    at android.app.ActivityThread.installProvider(ActivityThread.java:5366) 
                                                    at android.app.ActivityThread.installContentProviders(ActivityThread.java:4887) 
                                                    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4818) 
                                                    at android.app.ActivityThread.access$1600(ActivityThread.java:168) 
                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1440) 
                                                    at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                    at android.os.Looper.loop(Looper.java:150) 
                                                    at android.app.ActivityThread.main(ActivityThread.java:5665) 
                                                    at java.lang.reflect.Method.invoke(Native Method) 
                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:799) 
                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:689) 
                                                 Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.internal.zztv" on path: DexPathList[[zip file "/data/app/com.movisystem.flippycard-2/base.apk", zip file "/data/app/com.movisystem.flippycard-2/split_lib_dependencies_apk.apk", zip file "/data/app/com.movisystem.flippycard-2/split_lib_slice_0_apk.apk", zip file "/data/app/com.movisystem.flippycard-2/split_lib_slice_1_apk.apk", zip file "/data/app/com.movisystem.flippycard-2/split_lib_slice_2_apk.apk", zip file "/data/app/com.movisystem.flippycard-2/split_lib_slice_3_apk.apk", zip file "/data/app/com.movisystem.flippycard-2/split_lib_slice_4_apk.apk", zip file "/data/app/com.movisystem.flippycard-2/split_lib_slice_5_apk.apk", zip file "/data/app/com.movisystem.flippycard-2/split_lib_slice_6_apk.apk", zip file "/data/app/com.movisystem.flippycard-2/split_lib_slice_7_apk.apk", zip file "/data/app/com.movisystem.flippycard-2/split_lib_slice_8_apk.apk", zip file "/data/app/com.movisystem.flippycard-2/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.movisystem.flippycard-2/lib/arm64, /vendor/lib64, /system/lib64]]
                                                    at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                    at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                    at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                    at com.google.firebase.crash.internal.config.flag.Flags.<clinit>(Unknown Source) 
                                                    at com.google.firebase.crash.internal.config.flag.Flags.initialize(Unknown Source) 
                                                    at com.google.firebase.crash.FirebaseCrash.getInstance(Unknown Source) 
                                                    at java.lang.reflect.Method.invoke(Native Method) 
                                                    at com.google.firebase.FirebaseApp.zza(Unknown Source) 
                                                    at com.google.firebase.FirebaseApp.initializeApp(Unknown Source) 
                                                    at com.google.firebase.FirebaseApp.initializeApp(Unknown Source) 
                                                    at com.google.firebase.FirebaseApp.initializeApp(Unknown Source) 
                                                    at com.google.firebase.provider.FirebaseInitProvider.onCreate(Unknown Source) 
                                                    at android.content.ContentProvider.attachInfo(ContentProvider.java:1748) 
                                                    at android.content.ContentProvider.attachInfo(ContentProvider.java:1723) 
                                                    at com.google.firebase.provider.FirebaseInitProvider.attachInfo(Unknown Source) 
                                                    at android.app.ActivityThread.installProvider(ActivityThread.java:5366) 
                                                    at android.app.ActivityThread.installContentProviders(ActivityThread.java:4887) 
                                                    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4818) 
                                                    at android.app.ActivityThread.access$1600(ActivityThread.java:168) 
                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1440) 
                                                    at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                    at android.os.Looper.loop(Looper.java:150) 
                                                    at android.app.ActivityThread.main(ActivityThread.java:5665) 
                                                    at java.lang.reflect.Method.invoke(Native Method) 
                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:799) 
                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:689) 
                                                	Suppressed: java.lang.ClassNotFoundException: com.google.android.gms.internal.zztv
                                                    at java.lang.Class.classForName(Native Method)
                                                    at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                    at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                    at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                    		... 24 more
                                                 Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available`

What can I do to fix it?

**Comment by samtstern** [comment]
@EminDemiri please move this question to StackOverflow, there's not enough information to debug and it does not look like an issue with the code in this repository.
