### ISSUE TITLE
WakefulBroadcastReceiver

### ISSUE THREAD

**Issue by hdtuan87** [firebase/quickstart-android#263]
I see from fabric error log

    Fatal Exception: java.lang.RuntimeException: Unable to start receiver com.google.firebase.iid.FirebaseInstanceIdInternalReceiver: java.lang.IllegalStateException: Existing wake lock package name changed: com.android.calendar to com.bookmark.money
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:2733)
       at android.app.ActivityThread.-wrap14(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1422)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5452)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:762)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:652)
    Caused by java.lang.IllegalStateException: Existing wake lock package name changed: com.android.calendar to com.bookmark.money
       at android.os.Parcel.readException(Parcel.java:1607)
       at android.os.Parcel.readException(Parcel.java:1552)
       at android.os.IPowerManager$Stub$Proxy.acquireWakeLock(IPowerManager.java:384)
       at android.os.PowerManager$WakeLock.acquireLocked(PowerManager.java:1142)
       at android.os.PowerManager$WakeLock.acquire(PowerManager.java:1126)
       at android.support.v4.content.WakefulBroadcastReceiver.startWakefulService(WakefulBroadcastReceiver.java:100)
       at com.google.firebase.iid.zzg.zzb(Unknown Source)
       at com.google.firebase.iid.zzg.zzabU(Unknown Source)
       at com.google.firebase.iid.FirebaseInstanceIdInternalReceiver.onReceive(Unknown Source)
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:2726)
       at android.app.ActivityThread.-wrap14(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1422)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5452)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:762)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:652)

User uninstall my app because it drain battery. 
Please quick fix it.

**Comment by samtstern** [comment]
@hdtuan87 sorry we never got back to you on this.  In general when you file an issue we need more than just a stack trace.  We need some code or instructions to reproduce the issue, otherwise we can't debug.

I hope you figured out a fix since you filed this, good luck!
