### ISSUE TITLE
java.lang.IllegalStateException: Task is already complete

### ISSUE THREAD

**Issue by MIkeeJY** [firebase/quickstart-android#306]
Fatal Exception: java.lang.RuntimeException: Unable to destroy activity java.lang.IllegalStateException: Task is already complete
       at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4208)
       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4226)
       at android.app.ActivityThread.-wrap6(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1534)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6123)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
Caused by java.lang.IllegalStateException: Task is already complete
       at com.google.android.gms.common.internal.zzbo.zzu(Unknown Source)
       at com.google.android.gms.tasks.zzn.zzDH(Unknown Source)
       at com.google.android.gms.tasks.zzn.isComplete(Unknown Source)
       at com.google.android.gms.tasks.TaskCompletionSource.setResult(Unknown Source)
       at com.google.android.gms.internal.zzbeb.onDestroy(Unknown Source)
       at com.google.android.gms.internal.zzbeo.onDestroy(Unknown Source)
       at android.support.v4.app.Fragment.performDestroy(Fragment.java:2434)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1442)
       at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
       at android.support.v4.app.FragmentManagerImpl.dispatchDestroy(FragmentManager.java:2951)
       at android.support.v4.app.FragmentController.dispatchDestroy(FragmentController.java:271)
       at android.support.v4.app.FragmentActivity.onDestroy(FragmentActivity.java:390)
       at android.support.v7.app.AppCompatActivity.onDestroy(AppCompatActivity.java:209)
       at 
       at android.app.Activity.performDestroy(Activity.java:6874)
       at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1175)
       at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4195)
       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4226)
       at android.app.ActivityThread.-wrap6(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1534)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6123)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)

The exception occurs when users need to update google play service...

**Comment by MIkeeJY** [comment]
@samtstern

**Comment by MIkeeJY** [comment]
This error is located in the onDestroy method of the Startup page Activity

    @Override
    protected void onDestroy() {
            super.onDestroy(); //Located in ths line
}
