### ISSUE TITLE
how can i split this into two activity's 

### ISSUE THREAD

**Issue by oneilbogle1** [firebase/quickstart-android#364]
### Step 1: Are you in the right place?

  * For issues or feature requests related to the code **in this repository** file a Github issue.
    * If you are filing an issue about **FCM in the background** make sure to read [#4](https://github.com/firebase/quickstart-android/issues/4) and [#89](https://github.com/firebase/quickstart-android/issues/89) first!
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/) tagged appropriately.
  * For general Firebase discussion, use the [firebase-talk google group](https://groups.google.com/forum/#!forum/firebase-talk)
  * For help troubleshooting your application that does not fall under one of the above categories, reach out to the [personalized Firebase support channel](https://firebase.google.com/support/contact/troubleshooting/)

### Step 2: Describe your environment

  * Android device: _____
  * Android OS version: _____
  * Google Play Services version: _____
  * Firebase/Play Services SDK version: _____
  
#### Steps to reproduce:

  1. _____
  2. _____
  3. _____
  
#### Observed Results:

  * What happened?  This could be a description, `logcat` output, etc.
  
#### Expected Results:

  * What did you expect to happen?
  
#### Relevant Code:

  ```
  // TODO(you): code here to reproduce the problem
  ```

**Comment by kroikie** [comment]
@oneilbogle1 we would need more information to assist with your issue.

**Comment by oneilbogle1** [comment]
@kroikie  using two activities for firebase phone authentication   
https://stackoverflow.com/questions/46686891/using-two-activities-for-firebase-phone-authentication?noredirect=1#comment80321174_46686891

**Comment by kroikie** [comment]
@oneilbogle1 could you post the logcat messages you get when the crash occurs?

**Comment by oneilbogle1** [comment]
`Process: com.example.bogle.chatdemo2, PID: 32609
java.lang.IllegalArgumentException: Given String is empty or null
 at com.google.android.gms.common.internal.zzbo.zzcF(Unknown Source)
 at com.google.firebase.auth.PhoneAuthCredential.<init>(Unknown Source) 
 at com.google.firebase.auth.PhoneAuthProvider.getCredential(Unknown Source)
 at com.example.bogle.chatdemo2.PhoneVerAuthActivity.verifyPhoneNumberWithCode(PhoneVerAuthActivity.java:127)
 at com.example.bogle.chatdemo2.PhoneVerAuthActivity.onClick(PhoneVerAuthActivity.java:181)
 at android.view.View.performClick(View.java:6205)
 at android.widget.TextView.performClick(TextView.java:11103)
 at android.view.View$PerformClick.run(View.java:23653)
 at android.os.Handler.handleCallback(Handler.java:751)
 at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6682)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)`

**Comment by kroikie** [comment]
@oneilbogle1 looks like your second activity has an empty `verificationId` since you are not calling verifyPhoneNumber in the second activity verificationId is never set.
