### ISSUE TITLE
Failed to initialize crash reporting RuntimeException

### ISSUE THREAD

**Issue by austynmahoney** [firebase/quickstart-android#37]
Using Play Services 9.0.83 on a Nexus 5X I received the following stack trace when a crash occurred in my app.

```
E/DynamiteModule: Failed to load module descriptor class: Didn't find class "com.google.android.gms.dynamite.descriptors.com.google.android.gms.crash.ModuleDescriptor" on path: DexPathList[[zip file "/data/app/REDACTED-2/base.apk"],nativeLibraryDirectories=[/data/app/REDACTED/lib/arm64, /vendor/lib64, /system/lib64]]
E/Crash: Failed to initialize crash reporting
         java.lang.RuntimeException: com.google.android.gms.internal.zzqb$zza: Failed to instantiate module class: com.google.android.gms.crash.internal.api.CrashApiImpl
             at com.google.android.gms.internal.zzph.zztD(Unknown Source)
             at com.google.android.gms.crash.Crash.init(Unknown Source)
             at com.google.android.gms.crash.internal.provider.CrashInitContentProvider.onCreate(Unknown Source)
             at android.content.ContentProvider.attachInfo(ContentProvider.java:1748)
             at android.content.ContentProvider.attachInfo(ContentProvider.java:1723)
             at android.app.ActivityThread.installProvider(ActivityThread.java:5158)
             at android.app.ActivityThread.installContentProviders(ActivityThread.java:4753)
             at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4693)
             at android.app.ActivityThread.-wrap1(ActivityThread.java)
             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
             at android.os.Handler.dispatchMessage(Handler.java:102)
             at android.os.Looper.loop(Looper.java:148)
             at android.app.ActivityThread.main(ActivityThread.java:5422)
             at java.lang.reflect.Method.invoke(Native Method)
             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
          Caused by: com.google.android.gms.internal.zzqb$zza: Failed to instantiate module class: com.google.android.gms.crash.internal.api.CrashApiImpl
             at com.google.android.gms.internal.zzqb.zzdr(Unknown Source)
             at com.google.android.gms.internal.zzph.zztD(Unknown Source) 
             at com.google.android.gms.crash.Crash.init(Unknown Source) 
             at com.google.android.gms.crash.internal.provider.CrashInitContentProvider.onCreate(Unknown Source) 
             at android.content.ContentProvider.attachInfo(ContentProvider.java:1748) 
             at android.content.ContentProvider.attachInfo(ContentProvider.java:1723) 
             at android.app.ActivityThread.installProvider(ActivityThread.java:5158) 
             at android.app.ActivityThread.installContentProviders(ActivityThread.java:4753) 
             at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4693) 
             at android.app.ActivityThread.-wrap1(ActivityThread.java) 
             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405) 
             at android.os.Handler.dispatchMessage(Handler.java:102) 
             at android.os.Looper.loop(Looper.java:148) 
             at android.app.ActivityThread.main(ActivityThread.java:5422) 
             at java.lang.reflect.Method.invoke(Native Method) 
             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
          Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.crash.internal.api.CrashApiImpl" on path: DexPathList[[zip file "/data/user/0/com.google.android.gms/app_chimera/m/00000002/DynamiteModulesC_GmsCore_prodmnc_alldpi_release.apk"],nativeLibraryDirectories=[/data/user/0/com.google.android.gms/app_chimera/m/00000002/n/arm64-v8a, /vendor/lib64, /system/lib64]]
             at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
             at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
             at com.google.android.chimera.container.internal.DelegateLastPathClassLoader.loadClass(SourceFile:22)
             at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
             at com.google.android.gms.internal.zzqb.zzdr(Unknown Source) 
             at com.google.android.gms.internal.zzph.zztD(Unknown Source) 
             at com.google.android.gms.crash.Crash.init(Unknown Source) 
             at com.google.android.gms.crash.internal.provider.CrashInitContentProvider.onCreate(Unknown Source) 
             at android.content.ContentProvider.attachInfo(ContentProvider.java:1748) 
             at android.content.ContentProvider.attachInfo(ContentProvider.java:1723) 
             at android.app.ActivityThread.installProvider(ActivityThread.java:5158) 
             at android.app.ActivityThread.installContentProviders(ActivityThread.java:4753) 
             at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4693) 
             at android.app.ActivityThread.-wrap1(ActivityThread.java) 
             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405) 
             at android.os.Handler.dispatchMessage(Handler.java:102) 
             at android.os.Looper.loop(Looper.java:148) 
             at android.app.ActivityThread.main(ActivityThread.java:5422) 
             at java.lang.reflect.Method.invoke(Native Method) 
             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
         	Suppressed: java.lang.ClassNotFoundException: com.google.android.gms.crash.internal.api.CrashApiImpl
             at java.lang.Class.classForName(Native Method)
             at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
             at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
             at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
             at com.google.android.chimera.container.internal.FilteringClassLoader.loadClass(SourceFile:472)
             at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
             		... 19 more
          Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available

```

**Comment by samtstern** [comment]
@austynmahoney thanks for this bug report, I've forwarded the logs on to the Crash team and they will take a look.

**Comment by samtstern** [comment]
@austynmahoney in your stack trace I see `CrashInitProvider`

**Comment by austynmahoney** [comment]
Not pre-release, it would have been `9.0.0`, but possibly `9.0.2`. Sorry, I can't remember if we had updated to `9.0.2` before or after this happened.

Dependencies
```
compile 'com.google.firebase:firebase-core:9.0.2'
compile 'com.google.firebase:firebase-crash:9.0.2'
```

**Comment by samtstern** [comment]
Sorry for the lack of responses here!  I did follow up with the crash reporting team but they don't seen an obvious cause here and we're quite confused that you're seeing `CrashInitProvider` issues since that code is not part of the public SDK.

@austynmahoney there was a new SDK version released today (`9.2.0`).  Does this issue still happen with that SDK?

**Comment by austynmahoney** [comment]
I will upgrade our app and monitor for that crash.

**Comment by austynmahoney** [comment]
@samtstern I am upgrading to `9.2.0`. Is there a changelog somewhere I can take a look at?

**Comment by samtstern** [comment]
@austynmahoney there are two places you can look:

  * [Google Play Services release notes](https://developers.google.com/android/guides/releases#june_2016_-_v92)
  * [Firebase release notes](https://firebase.google.com/support/releases)

**Comment by austynmahoney** [comment]
Thanks for those links.

The Firebase Release Notes page is great, but I don't see `9.2.0` listed on the page. A changelog for each SDK would be great, as I am hesitant to upgrade without one. Plus how am I even supposed to know it has been updated?

**Comment by samtstern** [comment]
That's a good point, I will give your feedback to the page author and see how they feel about doing a more traditional release notes page with version-by-version diffs.  Also I'll look into getting an RSS or Twitter or some other push notification channel for interested devs (no promises though!).

**Comment by austynmahoney** [comment]
@samtstern Above and beyond man. Thanks again!

**Comment by samtstern** [comment]
@austynmahoney some improvements to the Firebase release notes are now published.  We went back and edited the last release to include the text below, and future releases will do the same:

> Version 9.2.0 of the Firebase SDK for Android is now available as part of the Google Play services 9.2 release. To install this SDK, see Add Firebase to your Android Project. This release includes a wide range of fixes and improvements, the most significant of which are summarized below.

We're also going to look into improving the general structure of the page, but that's more long term.

Back to the issue at hand: let me know how `9.2.0` works for you regarding Crash reporting.

**Comment by samtstern** [comment]
@austynmahoney any update on how the new SDK is working for you?

**Comment by austynmahoney** [comment]
I haven't seen that crash again.

**Comment by samtstern** [comment]
@austynmahoney thanks for the update.  Since we never got a reliable repro on our end and the symptom is fixed on your end I will close this issue.  Appreciate all the back and forth so far and please reach out if you get anything like this in the future.

**Comment by r-massanet** [comment]
I'm posting this here, because it seems pretty much the same error. Apologies if it is not the right place.

This happens with Firebase SDK 9.4.0 for Android.

> E/FirebaseCrash(11373): Failed to initialize crash reporting
> E/FirebaseCrash(11373): java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
> E/FirebaseCrash(11373): 	at android.os.Handler.<init>(Handler.java:200)
> E/FirebaseCrash(11373): 	at android.os.Handler.<init>(Handler.java:114)
> E/FirebaseCrash(11373): 	at com.google.firebase.crash.internal.api.FirebaseCrashApiImpl.init(:com.google.android.gms.DynamiteModulesC:1175)
> E/FirebaseCrash(11373): 	at bss.onTransact(:com.google.android.gms.DynamiteModulesC:60)
> E/FirebaseCrash(11373): 	at android.os.Binder.transact(Binder.java:380)
> E/FirebaseCrash(11373): 	at com.google.firebase.crash.internal.zzd$zza$zza.zza(Unknown Source)
> E/FirebaseCrash(11373): 	at com.google.firebase.crash.FirebaseCrash.<init>(Unknown Source)
> E/FirebaseCrash(11373): 	at com.google.firebase.crash.FirebaseCrash.getInstance(Unknown Source)
> E/FirebaseCrash(11373): 	at java.lang.reflect.Method.invoke(Native Method)
> E/FirebaseCrash(11373): 	at java.lang.reflect.Method.invoke(Method.java:372)
> E/FirebaseCrash(11373): 	at com.google.firebase.FirebaseApp.zza(Unknown Source)
> E/FirebaseCrash(11373): 	at com.google.firebase.FirebaseApp.initializeApp(Unknown Source)
> E/FirebaseCrash(11373): 	at com.google.firebase.FirebaseApp.initializeApp(Unknown Source)
> ... from our client code
