### ISSUE TITLE
Firebase API initialization failure.

### ISSUE THREAD

**Issue by yokei15** [firebase/quickstart-android#380]
```
 E/FirebaseApp: Firebase API initialization failure.
                                                                java.lang.reflect.InvocationTargetException
                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                    at com.google.firebase.FirebaseApp.zza(Unknown Source)
                                                                    at com.google.firebase.FirebaseApp.initializeApp(Unknown Source)
                                                                    at com.google.firebase.FirebaseApp.initializeApp(Unknown Source)
                                                                    at com.google.firebase.FirebaseApp.zzbu(Unknown Source)
                                                                    at com.google.firebase.provider.FirebaseInitProvider.onCreate(Unknown Source)
                                                                    at android.content.ContentProvider.attachInfo(ContentProvider.java:1748)
                                                                    at android.content.ContentProvider.attachInfo(ContentProvider.java:1723)
                                                                    at com.google.firebase.provider.FirebaseInitProvider.attachInfo(Unknown Source)
                                                                    at android.app.ActivityThread.installProvider(ActivityThread.java:5153)
                                                                    at android.app.ActivityThread.installContentProviders(ActivityThread.java:4748)
                                                                    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4688)
                                                                    at android.app.ActivityThread.-wrap1(ActivityThread.java)
                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                    at android.os.Looper.loop(Looper.java:148)
                                                                    at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                 Caused by: java.lang.IllegalAccessError: Method 'void android.support.v4.content.ContextCompat.<init>()' is inaccessible to class 'com.google.firebase.iid.zzg' (declaration of 'com.google.firebase.iid.zzg' appears in /data/app/com.cab.cabafrica-1/base.apk)
                                                                    at com.google.firebase.iid.zzg.zzeC(Unknown Source)
                                                                    at com.google.firebase.iid.zzg.<init>(Unknown Source)
                                                                    at com.google.firebase.iid.zzg.<init>(Unknown Source)
                                                                    at com.google.firebase.iid.zzd.zzb(Unknown Source)
                                                                    at com.google.firebase.iid.FirebaseInstanceId.getInstance(Unknown Source)
                                                                    at java.lang.reflect.Method.invoke(Native Method) 
                                                                    at com.google.firebase.FirebaseApp.zza(Unknown Source) 
                                                                    at com.google.firebase.FirebaseApp.initializeApp(Unknown Source) 
                                                                    at com.google.firebase.FirebaseApp.initializeApp(Unknown Source) 
                                                                    at com.google.firebase.FirebaseApp.zzbu(Unknown Source) 
                                                                    at com.google.firebase.provider.FirebaseInitProvider.onCreate(Unknown Source) 
                                                                    at android.content.ContentProvider.attachInfo(ContentProvider.java:1748) 
                                                                    at android.content.ContentProvider.attachInfo(ContentProvider.java:1723) 
                                                                    at com.google.firebase.provider.FirebaseInitProvider.attachInfo(Unknown Source) 
                                                                    at android.app.ActivityThread.installProvider(ActivityThread.java:5153) 
                                                                    at android.app.ActivityThread.installContentProviders(ActivityThread.java:4748) 
                                                                    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4688) 
                                                                    at android.app.ActivityThread.-wrap1(ActivityThread.java) 
                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405) 
                                                                    at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                    at android.os.Looper.loop(Looper.java:148) 
                                                                    at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                    at java.lang.reflect.Method.invoke(Native Method) 
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
```

In build.gradle
```
buildscript {
    repositories {
        mavenCentral()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:1.5.0'
        classpath 'com.google.gms:google-services:3.0.0'
    }
}

allprojects {
    buildDir = "C:/tmp/${rootProject.name}/${project.name}"
    repositories {
        jcenter()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

In app dependencies 
```
dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:multidex:1.0.1'
    compile 'com.android.support:appcompat-v7:25.3.1'
    compile 'com.android.support:support-v4:25.3.1'
    compile 'com.android.support:design:25.3.1'
    compile 'com.android.support:recyclerview-v7:25.3.1'
    compile 'com.android.support:cardview-v7:25.3.1'
    compile 'com.facebook.android:facebook-android-sdk:4.0.0'
    compile 'com.google.android.gms:play-services:9.0.0'
    compile 'com.google.firebase:firebase-messaging:9.0.0'
    compile 'com.google.firebase:firebase-ads:9.0.0'
    compile('com.crashlytics.sdk.android:crashlytics:2.6.8@aar') {
        transitive = true;
    }
}
apply plugin: 'com.google.gms.google-services'
```

**Comment by samtstern** [comment]
@yokei15 apologies for the late response.  There are a few things to note here:

1) You should **never** include this dependency!  It brings in all of the `play-services-{x}` libraries into your app at once.  Just remove this line.
```
compile 'com.google.android.gms:play-services:9.0.0'
```

2) Could you try updating dependencies to a later version?  That means change all the `25.3.1` dependencies to `26.0.1` or `27.0.0` and all the `9.0.0` dependencies to `11.4.2` or `11.6.0`.

**Comment by samtstern** [comment]
Closing here since the discussion seems to have gone stale.  We can re-open if anyone wants to keep discussing.
