### ISSUE TITLE
FCM Crash:Bad notification posted from package

### ISSUE THREAD

**Issue by overlooping** [firebase/quickstart-android#394]
* Android device: Samsung(SM-G610F,SM-G950F,Galaxy A5(2016),Galaxy A3(2016),SM-G955F....)
  * Android OS version: 7.0
  * Google Play Services version: 11.0.4
  * Firebase/Play Services SDK version: 11.0.4
  
#### crash log:
Fatal Exception: android.app.RemoteServiceException: Bad notification posted from package com.xxx.xxx: Couldn't expand RemoteViews for: StatusBarNotification(pkg=com.xxx.xxx user=UserHandle{0} id=0 tag=FCM-Notification:126882220 key=0|com.xxx.xxx|0|FCM-Notification:126882220|10173: Notification(pri=0 contentView=null vibrate=null sound=content://settings/system/notification_sound defaults=0x0 flags=0x10 color=0x00000000 vis=PRIVATE semFlags=0x0 semPriority=0))
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1813)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6776)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)

#### Steps to reproduce:
 
  1. push an message to old version app
  2. upgrade new app from google play store
  3. click the message push to device before
  4. app crash

**Comment by tamtom** [comment]
updates?

**Comment by sillysachin** [comment]
I am seeing 1000s of crashes in Crashlytics as we have monthly release cycle. Crashes when user when clicks notification to app navigation when app has updated.

**Comment by sillysachin** [comment]
Other References - 
https://github.com/OneSignal/OneSignal-Android-SDK/issues/263

**Comment by Pulimet** [comment]
I've opened an issue with this crash here: https://issuetracker.google.com/issues/119839527

**Comment by sillysachin** [comment]
> @sillysachin could you provide your code for handling the incoming notification?

I solved it by use of standard images instead of vector drawables. It was issue of Notification not being able to handle vector images.

**Comment by Pulimet** [comment]
I'm not using vector images and still got this crashes.

**Comment by JeffZane** [comment]
> I'm not using vector images and still got this crashes.

me too

**Comment by hayton** [comment]
> > I'm not using vector images and still got this crashes.
> 
> me too

Same. And I am getting this only on Samsung note 9 Android 8.0

**Comment by pengfeiliu123** [comment]
I still face this problem. How can I solve it ?
