### ISSUE TITLE
[invites] Invite button click crashes Google Play services with missing permission for android.permission.READ_CONTACTS

### ISSUE THREAD

**Issue by friedger** [firebase/quickstart-android#42]
The invite button does not work on Android 6.0.1, device A0001 due to a security exception after I clicked the button and selected an account. Please see below for the log:

```
06-07 17:40:15.586 26744-26755/? E/DatabaseUtils: Writing exception to parcel
                                                  java.lang.SecurityException: Permission Denial: reading com.android.providers.contacts.ContactsProvider2 uri content://com.android.contacts/contacts from pid=27333, uid=10013 requires android.permission.READ_CONTACTS, or grantUriPermission()
                                                      at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:605)
                                                      at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:480)
                                                      at android.content.ContentProvider$Transport.query(ContentProvider.java:211)
                                                      at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:112)
                                                      at android.os.Binder.execTransact(Binder.java:453)
06-07 17:40:15.613 27333-27333/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.google.android.gms.ui, PID: 27333
                                                   java.lang.RuntimeException: Unable to resume activity {com.google.android.gms/com.google.android.gms.appinvite.AppInviteActivity}: java.lang.SecurityException: Permission Denial: reading com.android.providers.contacts.ContactsProvider2 uri content://com.android.contacts/contacts from pid=27333, uid=10013 requires android.permission.READ_CONTACTS, or grantUriPermission()
                                                       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3147)
                                                       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3178)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1407)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:148)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5466)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                    Caused by: java.lang.SecurityException: Permission Denial: reading com.android.providers.contacts.ContactsProvider2 uri content://com.android.contacts/contacts from pid=27333, uid=10013 requires android.permission.READ_CONTACTS, or grantUriPermission()
                                                       at android.os.Parcel.readException(Parcel.java:1620)
                                                       at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
                                                       at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
                                                       at android.content.ContentProviderProxy.query(ContentProviderNative.java:421)
                                                       at android.content.ContentResolver.query(ContentResolver.java:493)
                                                       at android.content.ContentResolver.query(ContentResolver.java:435)
                                                       at dxl.<init>(SourceFile:109)
                                                       at dxl.<init>(SourceFile:85)
                                                       at dvq.onStart(SourceFile:10897)
                                                       at com.google.android.chimera.FragmentProxy.onStart(SourceFile:425)
                                                       at android.support.v4.app.Fragment.performStart(SourceFile:1986)
                                                       at ex.a(SourceFile:1102)
                                                       at ex.a(SourceFile:1248)
                                                       at dy.run(SourceFile:738)
                                                       at ex.i(SourceFile:1613)
                                                       at es.c(SourceFile:330)
                                                       at en.onResume(SourceFile:441)
                                                       at com.google.android.chimera.container.ActivityProxy.superOnResume(SourceFile:2373)
                                                       at com.google.android.chimera.Activity.onResume(SourceFile:357)
                                                       at com.google.android.chimera.Activity.publicOnResume(SourceFile:362)
                                                       at com.google.android.chimera.container.ActivityProxy.onResume(SourceFile:294)
                                                       at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1259)
                                                       at android.app.Activity.performResume(Activity.java:6327)
                                                       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3136)
                                                       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3178) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1407) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:148) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5466) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
```

**Comment by CodingDoug** [comment]
Did some troubleshooting with @friedger and we discovered that this problem was caused by Play Services being revoked the permission to read contacts.  The device in question is a OnePlus device with CyanogenMod 11.  It has a permissions manager called Privacy Guard that works similarly to the permissions management screens in Android M.  So I imagine this could theoretically happen on M devices as well.

**Comment by samtstern** [comment]
@CodingDoug thanks for digging!  So I think the bug here is that AppInvites is not properly checking for runtime permissions before launching the dialog.  I will report it, but since it's not a sample issue I am going to close this.

If there is progress, I will still update this thread.

**Comment by friedger** [comment]
It looks like that this has been fixed by an update of CM 13 (MHC19Q). At least I can't reproduce. Google Play Services do respect the permissions and does not show any suggestions if permissions are revoked.

My guess is that Privacy Guard did not communicate the permission correctly.
