### ISSUE TITLE
Firebase API initialization failure.

### ISSUE THREAD

**Issue by zhouxiaoqi2017** [firebase/quickstart-android#423]
```
02-07 18:30:27.524 18981-18981/com.mol.vt A/FirebaseApp: Firebase API initialization failure.
                                                         java.lang.reflect.InvocationTargetException
                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                             at java.lang.reflect.Method.invoke(Method.java:372)
                                                             at com.google.firebase.FirebaseApp.zza(Unknown Source)
                                                             at com.google.firebase.FirebaseApp.initializeApp(Unknown Source)
                                                             at com.google.firebase.FirebaseApp.initializeApp(Unknown Source)
                                                             at com.google.firebase.FirebaseApp.initializeApp(Unknown Source)
                                                             at com.google.firebase.provider.FirebaseInitProvider.onCreate(Unknown Source)
                                                             at android.content.ContentProvider.attachInfo(ContentProvider.java:1696)
                                                             at android.content.ContentProvider.attachInfo(ContentProvider.java:1671)
                                                             at com.google.firebase.provider.FirebaseInitProvider.attachInfo(Unknown Source)
                                                             at android.app.ActivityThread.installProvider(ActivityThread.java:4999)
                                                             at android.app.ActivityThread.installContentProviders(ActivityThread.java:4594)
                                                             at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4534)
                                                             at android.app.ActivityThread.access$1500(ActivityThread.java:151)
                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364)
                                                             at android.os.Handler.dispatchMessage(Handler.java:102)
                                                             at android.os.Looper.loop(Looper.java:135)
                                                             at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                             at java.lang.reflect.Method.invoke(Method.java:372)
                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
                                                          Caused by: java.lang.NoSuchMethodError: No virtual method zzbqp()Ljava/lang/String; in class Lcom/google/firebase/FirebaseApp; or its super classes (declaration of 'com.google.firebase.FirebaseApp' appears in /data/app/com.mol.vt-1/split_lib_dependencies_apk.apk)
                                                             at com.google.firebase.auth.FirebaseAuth.zzb(Unknown Source)
                                                             at com.google.firebase.auth.FirebaseAuth.getInstance(Unknown Source)
                                                             at java.lang.reflect.Method.invoke(Native Method) 
                                                             at java.lang.reflect.Method.invoke(Method.java:372) 
                                                             at com.google.firebase.FirebaseApp.zza(Unknown Source) 
                                                             at com.google.firebase.FirebaseApp.initializeApp(Unknown Source) 
                                                             at com.google.firebase.FirebaseApp.initializeApp(Unknown Source) 
                                                             at com.google.firebase.FirebaseApp.initializeApp(Unknown Source) 
                                                             at com.google.firebase.provider.FirebaseInitProvider.onCreate(Unknown Source) 
                                                             at android.content.ContentProvider.attachInfo(ContentProvider.java:1696) 
                                                             at android.content.ContentProvider.attachInfo(ContentProvider.java:1671) 
                                                             at com.google.firebase.provider.FirebaseInitProvider.attachInfo(Unknown Source) 
                                                             at android.app.ActivityThread.installProvider(ActivityThread.java:4999) 
                                                             at android.app.ActivityThread.installContentProviders(ActivityThread.java:4594) 
                                                             at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4534) 
                                                             at android.app.ActivityThread.access$1500(ActivityThread.java:151) 
                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364) 
                                                             at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                             at android.os.Looper.loop(Looper.java:135) 
                                                             at android.app.ActivityThread.main(ActivityThread.java:5254) 
                                                             at java.lang.reflect.Method.invoke(Native Method) 
                                                             at java.lang.reflect.Method.invoke(Method.java:372) 
                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) 

```

```groovy
dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support.constraint:constraint-layout:1.0.2'
    testCompile 'junit:junit:4.12'
    compile "com.android.support:appcompat-v7:$SUPPORT_LIBRARY",
            "com.android.support:recyclerview-v7:$SUPPORT_LIBRARY",
            "com.android.support:design:$SUPPORT_LIBRARY",
            "com.android.support:support-annotations:$SUPPORT_LIBRARY",
            "com.android.support:support-v4:$SUPPORT_LIBRARY",
            "com.android.support:support-v13:$SUPPORT_LIBRARY",
            "com.android.support:cardview-v7:$SUPPORT_LIBRARY"

    compile "com.google.firebase:firebase-core:$FIREBASE"
    compile "com.google.firebase:firebase-messaging:$FIREBASE"
}


SUPPORT_LIBRARY=26.0.2
FIREBASE=11.8.0
```

**Comment by samtstern** [comment]
@zhouxiaoqi2017 I can't help you with this issue as it is filed.  Please provide the information requested and I can re-open it if you want:

   * What code were you trying to run?
   * Does this happen on all devices?
   * What are you trying to do?
