### ISSUE TITLE
Fatal Exception: java.lang.IncompatibleClassChangeError: com.google.android.gms.auth.api.credentials.CredentialPickerConfig

### ISSUE THREAD

**Issue by sohailniazai** [firebase/quickstart-android#427]
I updated to firebase 11.8.0 due to crash on Connectivitychange in 11.6.0 but I got following crash . I am using accountkit in my app . Can you please help me with this issue. Thanks
Following is the stacktrace:
Fatal Exception: java.lang.IncompatibleClassChangeError: com.google.android.gms.auth.api.credentials.CredentialPickerConfig
       at com.google.android.gms.auth.api.credentials.CredentialPickerConfig$Builder.build(Unknown Source)
       at com.google.android.gms.auth.api.credentials.HintRequest$Builder.(Unknown Source)
       at com.facebook.accountkit.ui.PhoneLoginContentController$TopFragment.fillPhoneNumber(PhoneLoginContentController.java:414)
       at com.facebook.accountkit.ui.PhoneLoginContentController$TopFragment.onViewReadyWithState(PhoneLoginContentController.java:323)
       at com.facebook.accountkit.ui.ViewStateFragment.onActivityCreated(ViewStateFragment.java:66)
       at com.facebook.accountkit.ui.PhoneLoginContentController$TopFragment.onActivityCreated(PhoneLoginContentController.java:228)
       at android.app.Fragment.performActivityCreated(Fragment.java:2237)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:992)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1148)
       at android.app.BackStackRecord.run(BackStackRecord.java:793)
       at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1535)
       at android.app.FragmentController.execPendingActions(FragmentController.java:325)
       at android.app.Activity.performResume(Activity.java:6369)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3110)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3152)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2499)
       at android.app.ActivityThread.access$900(ActivityThread.java:157)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1356)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5525)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)

**Comment by samtstern** [comment]
@sohailniazai can you show me a few things:

- Your `build.gradle`
- The output of `./gradlew :app:androidDependencies`

Thanks!

**Comment by samtstern** [comment]
@sohailniazai since there hasn't been a response in 18 days I am going to close this issue.  If you still need help and can provide that info let me know.
