### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method on a null object reference: EmailPasswordActivity.createAccount

### ISSUE THREAD

**Issue by begunfx** [firebase/quickstart-android#456]
### Step 2: Describe your environment

  * Android device: Emulator (Nexus 6 API 25 x86)
  * Android OS version: 7.1.1
  * Google Play Services version: 3.2.0
  * Firebase/Play Services SDK version: 12.0.0
  
### Step 3: Describe the problem:
I'm trying to test out the quick start Auth test project, but when I try to create a new account after launching the EmailPasswordActivity I get a NullPointerException.

#### Steps to reproduce:

 1. Run app
2. Select Email/Password Activity
3. When the login screen appears enter email and password
4. select "create account"
  
#### Observed Results:

  03-25 14:41:08.278 6575-6575/com.google.firebase.quickstart.auth E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                   Process: com.google.firebase.quickstart.auth, PID: 6575
                                                                                   java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.android.gms.tasks.Task com.google.android.gms.common.api.GoogleApi.zzb(com.google.android.gms.common.api.internal.zzde)' on a null object reference
                                                                                       at com.google.android.gms.internal.zzdza.zzb(Unknown Source)
                                                                                       at com.google.android.gms.internal.zzdzh.zza(Unknown Source)
                                                                                       at com.google.firebase.auth.FirebaseAuth.createUserWithEmailAndPassword(Unknown Source)
                                                                                       at com.google.firebase.quickstart.auth.EmailPasswordActivity.createAccount(EmailPasswordActivity.java:89)
                                                                                       at com.google.firebase.quickstart.auth.EmailPasswordActivity.onClick(EmailPasswordActivity.java:235)
                                                                                       at android.view.View.performClick(View.java:5637)
                                                                                       at android.view.View$PerformClick.run(View.java:22429)
                                                                                       at android.os.Handler.handleCallback(Handler.java:751)
                                                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                       at android.os.Looper.loop(Looper.java:154)
                                                                                       at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
03-25 14:41:08.297 6575-6616/com.google.firebase.quickstart.auth W/DynamiteModule: Local module descriptor class for com.google.firebase.auth not found.
03-25 14:41:08.308 6575-6616/com.google.firebase.quickstart.auth W/GooglePlayServicesUtil: Google Play services out of date.  Requires 12210000 but found 1194748  
#### Expected Results:

To have account created successfully
  
#### Relevant Code:

  ```
Error has something to do with this block of code:

       // [START create_user_with_email]
        mAuth.createUserWithEmailAndPassword(email, password)
                .addOnCompleteListener(this, new OnCompleteListener<AuthResult>() {
                    @Override
                    public void onComplete(@NonNull Task<AuthResult> task) {
                        if (task.isSuccessful()) {
                            // Sign in success, update UI with the signed-in user's information
                            Log.d(TAG, "createUserWithEmail:success");
                            FirebaseUser user = mAuth.getCurrentUser();
                            updateUI(user);
                        } else {
                            // If sign in fails, display a message to the user.
                            Log.w(TAG, "createUserWithEmail:failure", task.getException());
                            Toast.makeText(EmailPasswordActivity.this, "Authentication failed.",
                                    Toast.LENGTH_SHORT).show();
                            updateUI(null);
                        }

                        // [START_EXCLUDE]
                        hideProgressDialog();
                        // [END_EXCLUDE]
                    }
                });
        // [END create_user_with_email]
    }
  ```

**Comment by begunfx** [comment]
Seems to be specific to the emulator.  I tried running this on my device and it ran successfully.

**Comment by samtstern** [comment]
@begunfx thanks for following up.  It's probably the case that your emulator has an out of date version of Google Play services and no way to update it.  I think this issue is already being tracked, but I will report it to the Auth folks anyway.

**Comment by samtstern** [comment]
You can see it in this log line:
```
03-25 14:41:08.308 6575-6616/com.google.firebase.quickstart.auth W/GooglePlayServicesUtil: Google Play services out of date.  Requires 12210000 but found 1194748
```

**Comment by begunfx** [comment]
Hi Sam, Thanks for the response to my post.  Yeah, after some investigating myself it seems that this is the issue.  However it isn't really clear how to get google services updated on the emulator.  The play store app isn't available for most emulator builds.  Do you have any suggestions?

**Comment by samtstern** [comment]
@begunfx normally if you update the emulator image itself (via Android studio) you will get an image with the latest version of Google Play services.

Sometimes there's a bit of lag on when this happens versus when the SDK comes out, especially on the older images.

I agree with what you're probably thinking - this is a bad developer experience - and I am doing what I can to advocate for a better system.

**Comment by begunfx** [comment]
Yeah, I'm having trouble with the emulators not running the latest Google Play services and it seems that several of the SDKs don't have the latest version (and have no way to easily update them).  This is definitely a problem as you pointed out for the developer experience, and any potential growth in adopting Firebase.  I'm just trying to get the Auth quick start app working so I can look to move my app over to using it.  This doesn't instill a lot of confidence in using Firebase.

Thanks for your support and response.  I'll try to find a workaround so I can get this working.

**Comment by samtstern** [comment]
Yep, you can follow along with me here:
https://issuetracker.google.com/74401291

Feel free to chime in!

**Comment by begunfx** [comment]
Thanks @samstern will do!
