### ISSUE TITLE
firebase real-time data error on Android studio. 

### ISSUE THREAD

**Issue by jay11234** [firebase/quickstart-android#465]
i guess these errors are from that android studio that cannot connect to Firebase. 
Any suggestions to solve this problems? thank you . 

```
04-07 18:35:13.271 25281-25281/com.example.a2015015407.edenparkproject E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.a2015015407.edenparkproject, PID: 25281
    com.google.firebase.database.DatabaseException: Invalid Firebase Database url specified
        at com.google.android.gms.internal.zzepd.zzqj(Unknown Source)
        at com.google.firebase.database.FirebaseDatabase.getInstance(Unknown Source)
        at com.google.firebase.database.FirebaseDatabase.getInstance(Unknown Source)
        at com.example.a2015015407.edenparkproject.CategoryFragment.onCreate(CategoryFragment.java:41)
        at android.support.v4.app.Fragment.performCreate(Fragment.java:2328)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1379)
        at android.support.v4.app.FragmentTransition.addToFirstInLastOut(FragmentTransition.java:1188)
        at android.support.v4.app.FragmentTransition.calculateFragments(FragmentTransition.java:1071)
        at android.support.v4.app.FragmentTransition.startTransitions(FragmentTransition.java:115)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2379)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2337)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2244)
        at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:702)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6077)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
     Caused by: java.net.URISyntaxException: Invalid scheme specified: Category
        at com.google.android.gms.internal.zzepd.zzqj(Unknown Source) 
        at com.google.firebase.database.FirebaseDatabase.getInstance(Unknown Source) 
        at com.google.firebase.database.FirebaseDatabase.getInstance(Unknown Source) 
        at com.example.a2015015407.edenparkproject.CategoryFragment.onCreate(CategoryFragment.java:41) 
        at android.support.v4.app.Fragment.performCreate(Fragment.java:2328) 
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1379) 
        at android.support.v4.app.FragmentTransition.addToFirstInLastOut(FragmentTransition.java:1188) 
        at android.support.v4.app.FragmentTransition.calculateFragments(FragmentTransition.java:1071) 
        at android.support.v4.app.FragmentTransition.startTransitions(FragmentTransition.java:115) 
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2379) 
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2337) 
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2244) 
        at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:702) 
        at android.os.Handler.handleCallback(Handler.java:751) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6077) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756) 
```

**Comment by samtstern** [comment]
@jay11234 can you show the code of this method? `com.example.a2015015407.edenparkproject.CategoryFragment.onCreate`

Also can you show the Firebase database URL you're using?

**Comment by jay11234** [comment]
package com.example.a2015015407.edenparkproject;

import android.os.Bundle;
import android.support.annotation.Nullable;
import android.support.v4.app.Fragment;
import android.support.v7.widget.LinearLayoutManager;
import android.support.v7.widget.RecyclerView;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Toast;

import com.example.a2015015407.edenparkproject.Interface.ItemClickListener;
import com.example.a2015015407.edenparkproject.Model.Category;
import com.example.a2015015407.edenparkproject.ViewHolder.CategoryViewHolder;
import com.firebase.ui.database.FirebaseRecyclerAdapter;
import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;
import com.squareup.picasso.Picasso;


public class CategoryFragment extends Fragment {

    View myFragment;

    RecyclerView listCategory;
    RecyclerView.LayoutManager layoutManager;
     FirebaseRecyclerAdapter<Category,CategoryViewHolder> adapter;
     FirebaseDatabase database;
     DatabaseReference categories;

    public static CategoryFragment newInstance(){
        CategoryFragment categoryFragment = new CategoryFragment();
        return categoryFragment;

    }

    @Override
    public void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        database=FirebaseDatabase.getInstance("Category");


    }

    @Nullable
    @Override
    public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
       myFragment=inflater.inflate(R.layout.fragment_category ,container,false);
        listCategory=(RecyclerView)myFragment.findViewById(R.id.listCategory);
        listCategory.setHasFixedSize(true);
        layoutManager=new LinearLayoutManager(container.getContext());
        listCategory.setLayoutManager(layoutManager);
        loadCategories();

       return myFragment;
    }

    private void loadCategories() {
        adapter=new FirebaseRecyclerAdapter<Category, CategoryViewHolder>(
                Category.class,
                R.layout.category_layout,
                CategoryViewHolder.class,
                categories

        ) {
            @Override
            protected void populateViewHolder(CategoryViewHolder viewHolder, final Category model, int position) {

                viewHolder.category_name.setText(model.getName());
                Picasso.with(getActivity()).load(model.getImage()).into(viewHolder.category_image);
                viewHolder.setItemClickListener(new ItemClickListener() {
                    @Override
                    public void onClick(View view, int position, boolean isLongClick) {
                        Toast.makeText( getActivity(),String.format("%s|%s",adapter.getRef(position).getKey(),model.getName()),Toast.LENGTH_SHORT).show();
                    }
                });
            }
        };

        adapter.notifyDataSetChanged();
        listCategory.setAdapter(adapter);

    }
}

**Comment by samtstern** [comment]
Closing this issue since it's been inactive for a month, hope you solved it!
