### ISSUE TITLE
Fatal Exception: java.lang.RuntimeException Unable to start activity ComponentInfo: java.lang.IllegalArgumentException: ApplicationId must be set.

### ISSUE THREAD

**Issue by ZebpayDipen** [firebase/quickstart-android#472]
android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2555)
--
  | android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:2629)
  | android.app.ActivityThread.access$800 (ActivityThread.java:182)
  | android.app.ActivityThread$H.handleMessage (ActivityThread.java:1474)
  | android.os.Handler.dispatchMessage (Handler.java:111)
  | android.os.Looper.loop (Looper.java:194)
  | android.app.ActivityThread.main (ActivityThread.java:5706)
  | java.lang.reflect.Method.invoke (Method.java)
  | java.lang.reflect.Method.invoke (Method.java:372)
  | com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1033)
  | com.android.internal.os.ZygoteInit.main (ZygoteInit.java:828)

Caused by java.lang.IllegalArgumentException
ApplicationId must be set.
utility.FirebaseUtils.getFirebaseOption

Caused by java.lang.IllegalArgumentException: ApplicationId must be set.
       at com.google.android.gms.common.internal.zzbq.zzh(Unknown Source)
       at com.google.firebase.FirebaseOptions$Builder.setApplicationId(Unknown Source)
       at utility.FirebaseUtils.getFirebaseOption(FirebaseUtils.java:1093)
       at utility.FirebaseUtils.getWarningMessageListener(FirebaseUtils.java:176)
      firebase.WarningMessageListener.startListener(WarningMessageListener.java:1037)
      BaseActivity.onCreate(BaseActivity.java:51)
      HomeActivity.onCreate(HomeActivity.java:208)
       at android.app.Activity.performCreate(Activity.java:6092)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1112)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2502)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2629)
       at android.app.ActivityThread.access$800(ActivityThread.java:182)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1474)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:194)
       at android.app.ActivityThread.main(ActivityThread.java:5706)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1033)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:828)

**Comment by samtstern** [comment]
@ZebpayDipen there's not enough information here.  Please try filing a new issue and filling our the whole template.  Let me know if you're confused by any of the instructions, happy to help!
