### ISSUE TITLE
Timestamp Object is not serializable

### ISSUE THREAD

**Issue by zdhruvit** [firebase/quickstart-android#524]
```
FATAL EXCEPTION: main
    Process: com.enfinilabs.beststockadvisor, PID: 15517
    java.lang.RuntimeException: Parcelable encountered IOException writing serializable object (name = com.enfinilabs.beststockadvisor.models.MetaModel)
        at android.os.Parcel.writeSerializable(Parcel.java:1394)
        at android.os.Parcel.writeValue(Parcel.java:1341)
        at android.os.Parcel.writeArrayMapInternal(Parcel.java:644)
        at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1313)
        at android.os.Bundle.writeToParcel(Bundle.java:1034)
        at android.os.Parcel.writeBundle(Parcel.java:669)
        at android.content.Intent.writeToParcel(Intent.java:8362)
        at android.app.ActivityManagerProxy.startActivity(ActivityManagerNative.java:2720)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1529)
        at android.app.Activity.startActivityForResult(Activity.java:4091)
        at android.support.v4.app.BaseFragmentActivityApi16.startActivityForResult(BaseFragmentActivityApi16.java:54)
        at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:68)
        at android.support.v4.app.ActivityCompat.startActivityForResult(ActivityCompat.java:233)
        at android.support.v4.app.FragmentActivity.startActivityFromFragment(FragmentActivity.java:825)
        at android.support.v4.app.FragmentActivity$HostCallbacks.onStartActivityFromFragment(FragmentActivity.java:939)
        at android.support.v4.app.Fragment.startActivity(Fragment.java:1002)
        at android.support.v4.app.Fragment.startActivity(Fragment.java:991)
        at com.enfinilabs.beststockadvisor.home.PublicCallFragment$1$1.onClick(PublicCallFragment.java:169)
        at android.view.View.performClick(View.java:5246)
        at android.view.View$PerformClick.run(View.java:21256)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:145)
        at android.app.ActivityThread.main(ActivityThread.java:6912)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
     Caused by: java.io.NotSerializableException: com.google.firebase.Timestamp
        at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1344)
        at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1651)
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1497)
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1461)
        at java.io.ObjectOutputStream.writeFieldValues(ObjectOutputStream.java:959)
        at java.io.ObjectOutputStream.defaultWriteObject(ObjectOutputStream.java:360)
        at java.io.ObjectOutputStream.writeHierarchy(ObjectOutputStream.java:1054)
        at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1384)
        at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1651)
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1497)
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1461)
        at java.io.ObjectOutputStream.writeFieldValues(ObjectOutputStream.java:959)
        at java.io.ObjectOutputStream.defaultWriteObject(ObjectOutputStream.java:360)
        at java.io.ObjectOutputStream.writeHierarchy(ObjectOutputStream.java:1054)
        at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1384)
        at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1651)
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1497)
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1461)
        at android.os.Parcel.writeSerializable(Parcel.java:1389)
        at android.os.Parcel.writeValue(Parcel.java:1341) 
        at android.os.Parcel.writeArrayMapInternal(Parcel.java:644) 
        at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1313) 
        at android.os.Bundle.writeToParcel(Bundle.java:1034) 
        at android.os.Parcel.writeBundle(Parcel.java:669) 
        at android.content.Intent.writeToParcel(Intent.java:8362) 
        at android.app.ActivityManagerProxy.startActivity(ActivityManagerNative.java:2720) 
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1529) 
        at android.app.Activity.startActivityForResult(Activity.java:4091) 
        at android.support.v4.app.BaseFragmentActivityApi16.startActivityForResult(BaseFragmentActivityApi16.java:54) 
        at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:68) 
        at android.support.v4.app.ActivityCompat.startActivityForResult(ActivityCompat.java:233) 
        at android.support.v4.app.FragmentActivity.startActivityFromFragment(FragmentActivity.java:825) 
        at android.support.v4.app.FragmentActivity$HostCallbacks.onStartActivityFromFragment(FragmentActivity.java:939) 
        at android.support.v4.app.Fragment.startActivity(Fragment.java:1002) 
        at android.support.v4.app.Fragment.startActivity(Fragment.java:991) 
        at com.enfinilabs.beststockadvisor.home.PublicCallFragment$1$1.onClick(PublicCallFragment.java:169) 
        at android.view.View.performClick(View.java:5246) 
        at android.view.View$PerformClick.run(View.java:21256) 
        at android.os.Handler.handleCallback(Handler.java:739) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:145) 
        at android.app.ActivityThread.main(ActivityThread.java:6912) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199) 
```

The Admin model

```java
public class AdminModel implements Serializable {

    private String email;
    private Timestamp timestamp;
    private String uid;

    public AdminModel() {
    }

    public AdminModel(String email, Timestamp timestamp, String uid) {
        this.email = email;
        this.timestamp = timestamp;
        this.uid = uid;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @ServerTimestamp
    public Timestamp getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(Timestamp timestamp) {
        this.timestamp = timestamp;
    }

    public String getUid() {
        return uid;
    }

    public void setUid(String uid) {
        this.uid = uid;
    }
}
```

This is the code where i try to pass

```
Intent intent = new Intent(getActivity(), CallMainActivity.class);
intent.putExtra("model", model.getMetadata().getUpdated_by());
intent.putExtra("theID", documentSnapshot.getId());
startActivity(intent);
```

**Comment by samtstern** [comment]
@zdhruvit Timestamp is just a `long nanoseconds` and `int seconds` so it's easily `Parcelable`.  `Serializable` is not recommended on Android.

I will file a FR for the class to come with a `Parcelable` implementation.

**Comment by samtstern** [comment]
As of version `17.0.3` timestamp is now `Parcelable`
