### ISSUE TITLE
Firebase version:9.4.0, report: java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by javanal** [firebase/quickstart-android#537]
Back traces starts.
java.lang.IllegalArgumentException
	at android.os.Parcel.nativeAppendFrom(Native Method)
	at android.os.Parcel.appendFrom(Parcel.java:449)
	at android.os.BaseBundle.<init>(BaseBundle.java:126)
	at android.os.Bundle.<init>(Bundle.java:102)
	at android.content.Intent.getExtras(Intent.java:5870)
	at com.google.firebase.messaging.FirebaseMessagingService.zzm(FirebaseMessagingService.java)
	at com.google.firebase.iid.zzb$2.run(zzb.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)
Back traces end.

**Comment by samtstern** [comment]
@javanal I apologize for not responding early, but this is not enough information to debug.  From the title it seems like you're using SDK version `9.4.0`, which is very old.  So I would recommend:

- Updating, if you can.
- Filing a new issue here and filling out the whole issue template so I can help you.
