### ISSUE TITLE
Firebase version:9.4.0, report: java.lang.NullPointerException: com.google.firebase.messaging.FirebaseMessagingService.zzm

### ISSUE THREAD

**Issue by javanal** [firebase/quickstart-android#538]
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.os.Parcel.dataSize()' on a null object reference
	at android.os.BaseBundle.(BaseBundle.java:164)
	at android.os.Bundle.(Bundle.java:106)
	at android.content.Intent.getExtras(Intent.java:7186)
	at com.google.firebase.messaging.FirebaseMessagingService.zzm(FirebaseMessagingService.java)
	at com.google.firebase.iid.zzb$2.run(zzb.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:762)
Back traces end.

**Comment by samtstern** [comment]
@javanal there is not enough information here to help you, and also version `9.4.0` is extremely old and we definitely recommend upgrading!

You can try opening another issue if you want, but please fill out the entire template.
