### ISSUE TITLE
NullPointer Exception in Parsing Error while parsing timestamp in GCM event : FireBaseMessaging

### ISSUE THREAD

**Issue by mohittanwar94** [firebase/quickstart-android#588]
every time we fire notification without data message from server we got null pointer exception in logcat .

  * Android device:Any Device
  * Android OS version: Any OS version
  * Google Play Services version:'com.google.gms:google-services:4.0.1'
  * Firebase/Play Services SDK version: com.google.firebase:firebase-core:16.0.1
                                                              com.google.firebase:firebase-messaging:17.1.0

Manifiest

```xml
        <service android:name=".notification.MyFirebaseMessagingService">
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT" />
            </intent-filter>
        </service>

        <service android:name=".notification.MyFirebaseInstanceIDService">
            <intent-filter>
                <action android:name="com.google.firebase.INSTANCE_ID_EVENT" />
            </intent-filter>
        </service>
```
FireBaseMessaging.java

```java
public class MyFirebaseMessagingService extends FirebaseMessagingService {
    public static int notification_count = 0;
    public static NotificationChannel mChannel = null;

    @Override
    public void onMessageReceived(RemoteMessage remoteMessage) {
        try {
            Map<String, String> data = remoteMessage.getData();
            UserInfo userInfo = UserInfo.getInstance(this);
            if (data.size() > 0) {
               //handle app have some data
            }else {
     
                String body = remoteMessage.getNotification().getBody();
                String title = remoteMessage.getNotification().getTitle();
                alertDialogFCMNotification(userInfo, title, body);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
```

```
FirebaseMessaging: Error while parsing timestamp in GCM event
    java.lang.NumberFormatException: Invalid int: "null"
        at java.lang.Integer.invalidInt(Integer.java:138)
        at java.lang.Integer.parseInt(Integer.java:358)
        at java.lang.Integer.parseInt(Integer.java:334)
        at com.google.firebase.messaging.zzb.zzc(Unknown Source)
        at com.google.firebase.messaging.zzb.zze(Unknown Source)
        at com.google.firebase.messaging.FirebaseMessagingService.zzd(Unknown Source)
        at com.google.firebase.iid.zzc.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source)
        at java.lang.Thread.run(Thread.java:818)
08-08 16:44:14.034 22120-22167/? W/FirebaseMessaging: Error while parsing timestamp in GCM event
    java.lang.NumberFormatException: Invalid int: "null"
        at java.lang.Integer.invalidInt(Integer.java:138)
        at java.lang.Integer.parseInt(Integer.java:358)
        at java.lang.Integer.parseInt(Integer.java:334)
        at com.google.firebase.messaging.zzb.zzc(Unknown Source)
        at com.google.firebase.messaging.zzb.zzh(Unknown Source)
        at com.google.firebase.messaging.FirebaseMessagingService.zzd(Unknown Source)
        at com.google.firebase.iid.zzc.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source)
        at java.lang.Thread.run(Thread.java:818)
```

1. fire any notification from firebase console to particular device logcat always show above log
  
timestamp value always come null instead of time stamp. we added a extra key in notification (timestamp) but not working

**Comment by tolstikhell** [comment]
+

**Comment by samtstern** [comment]
Hmmm I did some digging in the source code and this seems to come from the integration between Cloud Messaging and Analytics.

@kroikie do you know anything about this?

**Comment by SPodjasek** [comment]
There's a duplicate issue in flutter/flutter#19004 but the root cause is probably here

**Comment by SPodjasek** [comment]
It seems that `com.google.firebase:firebase-messaging:17.3.0` got this fixed

**Comment by samtstern** [comment]
@SPodjasek thanks for following up!
