### ISSUE TITLE
Error on getting Realtime Database reference in service

### ISSUE THREAD

**Issue by ch-muhammad-adil** [firebase/quickstart-android#64]
I am getting error:
 

> 06-24 10:41:36.497 17316-17316/com.example.waseem.geolocation:location_service E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                                 Process: com.example.waseem.geolocation:location_service, PID: 17316
                                                                                                 java.lang.RuntimeException: Unable to instantiate service com.example.waseem.geolocation.LocationService: java.lang.IllegalStateException: FirebaseApp with name [DEFAULT] doesn't exist. 
                                                                                                     at android.app.ActivityThread.handleCreateService(ActivityThread.java:3085)
                                                                                                     at android.app.ActivityThread.access$1900(ActivityThread.java:172)
                                                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1505)
                                                                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                                     at android.os.Looper.loop(Looper.java:145)
                                                                                                     at android.app.ActivityThread.main(ActivityThread.java:5832)
                                                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                                                     at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
                                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
                                                                                                  Caused by: java.lang.IllegalStateException: FirebaseApp with name [DEFAULT] doesn't exist. 
                                                                                                     at com.google.firebase.FirebaseApp.getInstance(Unknown Source)
                                                                                                     at com.google.firebase.FirebaseApp.getInstance(Unknown Source)
                                                                                                     at com.google.firebase.database.FirebaseDatabase.getInstance(Unknown Source)
                                                                                                     at com.example.waseem.geolocation.LocationService.<init>(LocationService.java:34)
                                                                                                     at java.lang.reflect.Constructor.newInstance(Native Method)
                                                                                                     at java.lang.Class.newInstance(Class.java:1650)
                                                                                                     at android.app.ActivityThread.handleCreateService(ActivityThread.java:3082)
                                                                                                     at android.app.ActivityThread.access$1900(ActivityThread.java:172) 
                                                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1505) 
                                                                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                                     at android.os.Looper.loop(Looper.java:145) 
                                                                                                     at android.app.ActivityThread.main(ActivityThread.java:5832) 
                                                                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                     at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399) 
                                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194) `. 

on

    DatabaseReference mDatabase = FirebaseDatabase.getInstance().getReference(); 

statement in service but its works fine in activity.

**Comment by samtstern** [comment]
@ch-muhammad-adil are you making any calls to the service in your `Application`'s `onCreate` method?  FirebaseApp is automatically initialized by a `ContentProvider` but this does not happen until after the `Application#onCreate` method has been called.

**Comment by ch-muhammad-adil** [comment]
no I am starting service from activity using this method startService(intent) and service is sticky

**Comment by samtstern** [comment]
@ch-muhammad-adil is the service running in the same process as your Activity?  If it's not, you would have an `android:process="..."` entry in the `AndroidManfiest.xml` for the `service`.

**Comment by ch-muhammad-adil** [comment]
how chould I make sure both run in same thread?

**Comment by samtstern** [comment]
@ch-muhammad-adil glad this worked for you, thanks for following up.

**Comment by pastillas** [comment]
good evening sir, I also experience this exception but in my case - I want my service(receiving child events) to run in separate process so that it still running whenever the main thread(App) is stopped or killed. how do I do this? hoping for your kind response. tnx :)

**Comment by samtstern** [comment]
@pastillas could you post your question on StackOverflow and include some code to show your particular situation?  That would be a better place to address this.

**Comment by pastillas** [comment]
[http://stackoverflow.com/questions/39642304/unable-to-get-databasereference-and-firebaseauth-currentuser-on-a-remoteseparat](here) is my question sir. tnx :)

**Comment by pastillas** [comment]
http://stackoverflow.com/questions/39642304/unable-to-get-databasereference-and-firebaseauth-currentuser-on-a-remoteseparat here is link sir thanks :)
