### ISSUE TITLE
RuntimeException: java.lang.reflect.InvocationTargetException When update data to Firebase

### ISSUE THREAD

**Issue by Thien658jjh** [firebase/quickstart-android#688]
I have this problem when I want to update the value of the firebase:

```
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at com.google.firebase.database.obfuscated.zzbw$zza.zza(com.google.firebase:firebase-database@@16.0.2:649)
        at com.google.firebase.database.obfuscated.zzbw.zzc(com.google.firebase:firebase-database@@16.0.2:167)
        at com.google.firebase.database.obfuscated.zzbw.zzb(com.google.firebase:firebase-database@@16.0.2:47)
        at com.google.firebase.database.obfuscated.zzbw$zza.zza(com.google.firebase:firebase-database@@16.0.2:663)
        at com.google.firebase.database.obfuscated.zzbw.zzc(com.google.firebase:firebase-database@@16.0.2:167)
        at com.google.firebase.database.obfuscated.zzbw.zza(com.google.firebase:firebase-database@@16.0.2:60)
        at com.google.firebase.database.DatabaseReference.zza(com.google.firebase:firebase-database@@16.0.2:292)
```
My code:
```
    private void saveToFirebase(TextHighlight textHighlight, String idStory, String userID) {
        if (databaseReference == null)
            databaseReference = FirebaseDatabase.getInstance().getReference();
        if (BuildConfig.DEBUG) {
            databaseReference.child("DEBUG").child(Utils.FB_USER_DATA).child(Utils.FB_NOTES_HIGHLIGHT)
                    .child(userID).child(idStory).child(textHighlight.getId()).setValue(textHighlight);
        } else {
            databaseReference.child(Utils.FB_USER_DATA).child(Utils.FB_NOTES_HIGHLIGHT)
                    .child(userID).child(idStory).child(textHighlight.getId()).setValue(textHighlight);
        }
    }
```
This one when I saved to Firebase
```
  TextHighlight textHighlight = new TextHighlight();
     //set data
        saveToFirebase(textHighlight, idStory, userID);
```

Gotting the error when the method below called to `saveToFirebase()`
```
    private void getTextHighlightRealm(String storyID, String storyContent) {
        StoryHighlight storyHighlight = mRealmController.getStoryHighlight(storyID);
      
        List<TextHighlight> textHighlights = new ArrayList<>(storyHighlight.getListHighlight());
        for (TextHighlight textHighlight : textHighlights) {
            //something else
             saveToFirebase(textHighlight, storyID, getCurrentUser());
        }
    }
```

And this is more detail:
At the first time, I created datas, and saved in to Firebase via `saveToFirebase` method ^^^^. It worked perfectly. But when user don't connect to internet, I saved in to Realm, update that datas to Firebase when user have connect to the internet again. 
I've research but did not get anything. Plz help me :'(

**Comment by etman55** [comment]
I have the same issue and this is my log 
```
2019-02-15 19:25:41.718 24055-24055/com.codeblue.codeblue E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.codeblue.codeblue, PID: 24055
    java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at com.google.firebase.database.core.utilities.encoding.CustomClassMapper$BeanMapper.serialize(com.google.firebase:firebase-database@@16.0.5:649)
        at com.google.firebase.database.core.utilities.encoding.CustomClassMapper.serialize(com.google.firebase:firebase-database@@16.0.5:167)
        at com.google.firebase.database.core.utilities.encoding.CustomClassMapper.convertToPlainJavaTypes(com.google.firebase:firebase-database@@16.0.5:60)
        at com.google.firebase.database.DatabaseReference.setValueInternal(com.google.firebase:firebase-database@@16.0.5:292)
        at com.google.firebase.database.DatabaseReference.setValue(com.google.firebase:firebase-database@@16.0.5:166)
        at com.codeblue.codeblue.ui.profile.ProfileFragment$onActivityResult$1.onSuccess(ProfileFragment.kt:172)
        at com.codeblue.codeblue.ui.profile.ProfileFragment$onActivityResult$1.onSuccess(ProfileFragment.kt:40)
        at com.google.firebase.storage.StorageTask.lambda$new$0(com.google.firebase:firebase-storage@@16.0.5:125)
        at com.google.firebase.storage.StorageTask$$Lambda$1.raise(Unknown Source:6)
        at com.google.firebase.storage.TaskListenerImpl.lambda$onInternalStateChanged$2(com.google.firebase:firebase-storage@@16.0.5:94)
        at com.google.firebase.storage.TaskListenerImpl$$Lambda$3.run(Unknown Source:6)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:6981)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.google.firebase.database.core.utilities.encoding.CustomClassMapper$BeanMapper.serialize(com.google.firebase:firebase-database@@16.0.5:645)
        at com.google.firebase.database.core.utilities.encoding.CustomClassMapper.serialize(com.google.firebase:firebase-database@@16.0.5:167) 
        at com.google.firebase.database.core.utilities.encoding.CustomClassMapper.convertToPlainJavaTypes(com.google.firebase:firebase-database@@16.0.5:60) 
        at com.google.firebase.database.DatabaseReference.setValueInternal(com.google.firebase:firebase-database@@16.0.5:292) 
        at com.google.firebase.database.DatabaseReference.setValue(com.google.firebase:firebase-database@@16.0.5:166) 
        at com.codeblue.codeblue.ui.profile.ProfileFragment$onActivityResult$1.onSuccess(ProfileFragment.kt:172) 
        at com.codeblue.codeblue.ui.profile.ProfileFragment$onActivityResult$1.onSuccess(ProfileFragment.kt:40) 
        at com.google.firebase.storage.StorageTask.lambda$new$0(com.google.firebase:firebase-storage@@16.0.5:125) 
        at com.google.firebase.storage.StorageTask$$Lambda$1.raise(Unknown Source:6) 
        at com.google.firebase.storage.TaskListenerImpl.lambda$onInternalStateChanged$2(com.google.firebase:firebase-storage@@16.0.5:94) 
        at com.google.firebase.storage.TaskListenerImpl$$Lambda$3.run(Unknown Source:6) 
        at android.os.Handler.handleCallback(Handler.java:873) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:6981) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445) 
     Caused by: java.lang.IllegalStateException: Task is not yet complete
        at com.google.android.gms.common.internal.Preconditions.checkState(Unknown Source:29)
        at com.google.android.gms.tasks.zzu.zzb(Unknown Source:121)
        at com.google.android.gms.tasks.zzu.getResult(Unknown Source:12)
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.google.firebase.database.core.utilities.encoding.CustomClassMapper$BeanMapper.serialize(com.google.firebase:firebase-database@@16.0.5:645) 
        at com.google.firebase.database.core.utilities.encoding.CustomClassMapper.serialize(com.google.firebase:firebase-database@@16.0.5:167) 
        at com.google.firebase.database.core.utilities.encoding.CustomClassMapper.convertToPlainJavaTypes(com.google.firebase:firebase-database@@16.0.5:60) 
        at com.google.firebase.database.DatabaseReference.setValueInternal(com.google.firebase:firebase-database@@16.0.5:292) 
        at com.google.firebase.database.DatabaseReference.setValue(com.google.firebase:firebase-database@@16.0.5:166) 
        at com.codeblue.codeblue.ui.profile.ProfileFragment$onActivityResult$1.onSuccess(ProfileFragment.kt:172) 
        at com.codeblue.codeblue.ui.profile.ProfileFragment$onActivityResult$1.onSuccess(ProfileFragment.kt:40) 
        at com.google.firebase.storage.StorageTask.lambda$new$0(com.google.firebase:firebase-storage@@16.0.5:125) 
        at com.google.firebase.storage.StorageTask$$Lambda$1.raise(Unknown Source:6) 
        at com.google.firebase.storage.TaskListenerImpl.lambda$onInternalStateChanged$2(com.google.firebase:firebase-storage@@16.0.5:94) 
        at com.google.firebase.storage.TaskListenerImpl$$Lambda$3.run(Unknown Source:6) 
        at android.os.Handler.handleCallback(Handler.java:873) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:6981) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
``` 

and this happens in this part 
```
val fileStorage = mStorageRef.child("profile_images")
                            .child("profile_" + mCurrentUser.uid + "." + getFileExtension(imagePath))
                        fileStorage.putFile(imagePath).addOnSuccessListener { taskSnapshot ->
                            mUserDatabase.child("Users").child(mCurrentUser.uid)
                                .child("image").setValue(taskSnapshot.storage.downloadUrl)
                        }.addOnFailureListener { e ->
                            Log.d(TAG, "onFailure: " + e.message!!)
                        }
```

**Comment by samtstern** [comment]
I know this response is wayyyy too late but I think this issue comes from the face that `getDownloadUrl()` returns a task which is not a valid argument for `setValue`:
https://firebase.google.com/docs/reference/android/com/google/firebase/storage/StorageReference#getDownloadUrl()
