### ISSUE TITLE
FirebaseRemoteConfig Unknown Error: 'long com.google.android.gms.internal.config.j.b()' on a null object reference

### ISSUE THREAD

**Issue by fikrirazzaq** [firebase/quickstart-android#695]
I received this error log in a FirebaseRemoteConfig.

> Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'long com.google.android.gms.internal.config.j.b()' on a null object reference
       at com.google.android.gms.internal.config.zzan.run(Unknown Source)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:762)
  
The problem is I cant find a way to reproduce this error. But I'm sure this is FirebaseRemoteConfig error after I found the class "zzan" in the firebase-config library.

I tried to update the  gradle and plugin version but the error keeps showing in the crahslytics.

The libs:
`implementation 'com.google.firebase:firebase-core:16.0.3'`
`implementation 'com.google.firebase:firebase-config:16.0.0'`
`implementation 'com.google.gms:google-services:4.0.1'`
`implementation 'com.google.android.gms:play-services-plus:15.0.1'`

`classpath 'com.android.tools.build:gradle:3.1.4'`
`classpath 'com.google.gms:google-services:4.0.1'`
`distributionUrl=https\://services.gradle.org/distributions/gradle-4.6-all.zip`

**Comment by ShrutiSarraf** [comment]
@samtstern 

It is our most occurring crash. By when can we expect this one to get fixed? Also, is there any work around to avoid this?

We are unable to reproduce it at our end. These are the logs from Crashlytics. 

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'long com.google.android.gms.internal.config.j.b()' on a null object reference
       at com.google.android.gms.internal.config.zzan.run(Unknown Source)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)
```
