### ISSUE TITLE
Using Firebase invites v16.0.5 fails gradle sync

### ISSUE THREAD

**Issue by raunakyadav** [firebase/quickstart-android#753]
* Android device: Samsung Galaxy S6
  * Android OS version: 7.0 
  * Google play services version : latest for all dependencies.
  * Firebase invites version : 16.0.5 

Steps  : Simply updating to 16.0.5 in gradle causes sync to fail.
  api 'com.google.firebase:firebase-invites:16.0.5'
   
Build Exception : 
```
org.gradle.api.resources.ResourceException: Could not get resource 'https://dl.google.com/dl/android/maven2/com/google/firebase/firebase-invites/16.0.5/firebase-invites-16.0.5-javadoc.jar'.
	at org.gradle.internal.resource.ResourceExceptions.failure(ResourceExceptions.java:74)
	at org.gradle.internal.resource.ResourceExceptions.getFailed(ResourceExceptions.java:57)
	at org.gradle.internal.resource.transfer.AccessorBackedExternalResource.withContentIfPresent(AccessorBackedExternalResource.java:146)
	at org.gradle.internal.resource.BuildOperationFiringExternalResourceDecorator$11.call(BuildOperationFiringExternalResourceDecorator.java:237)
	at org.gradle.internal.resource.BuildOperationFiringExternalResourceDecorator$11.call(BuildOperationFiringExternalResourceDecorator.java:229)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:350)
	at  
 ....
Caused by: java.io.IOException: Response 204: No Content has no content!
	at org.gradle.internal.resource.transport.http.HttpResponseResource.openStream(HttpResponseResource.java:123)
	at org.gradle.internal.resource.transfer.ProgressLoggingExternalResourceAccessor$ProgressLoggingExternalResource.openStream(ProgressLoggingExternalResourceAccessor.java:60)
	at org.gradle.internal.resource.transfer.AccessorBackedExternalResource.withContentIfPresent(AccessorBackedExternalResource.java:135)
	... 132 more
```

This is the latest version as mentioned on firebase page : https://firebase.google.com/support/release-notes/android
I am trying to update this dependency as it clashes with other google play service dependencies.
Please help look. Thanks.

**Comment by samtstern** [comment]
@raunakyadav thanks for filing this issue!  We think there was an error with our JavaDoc pipeline in this release and are looking into it.

**Comment by samtstern** [comment]
This issue has been fixed.
