### ISSUE TITLE
OutOfMemoryError Crash in MLkit

### ISSUE THREAD

**Issue by onlymnsh** [firebase/quickstart-android#775]
### Step 2: Describe your environment

  * Android device: 10Or
  * Android OS version: Oreo 8.1.0
  * Google Play Services version:14.7.99
  
### Step 3: Describe the problem:
```
 java.lang.OutOfMemoryError: Failed to allocate a 1072831 byte allocation with 212008 free bytes and 207KB until OOM, max allowed footprint 201326592, growth limit 201326592
        at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
        at java.nio.DirectByteBuffer$MemoryRef.<init>(DirectByteBuffer.java:71)
        at java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:240)
        at com.google.firebase.samples.apps.mlkit.java.custommodel.CustomImageClassifier.convertBitmapToByteBuffer(CustomImageClassifier.java:264)
        at com.google.firebase.samples.apps.mlkit.java.custommodel.CustomImageClassifier.classifyFrame(CustomImageClassifier.java:208)
        at com.google.firebase.samples.apps.mlkit.java.custommodel.CustomImageClassifierProcessor.process(CustomImageClassifierProcessor.java:61)
        at com.google.firebase.samples.apps.mlkit.common.CameraSource$FrameProcessingRunnable.run(CameraSource.java:714)
        at java.lang.Thread.run(Thread.java:764)
```

#### Steps to reproduce:

  1. LivePreviewActivity in Kotlin and choose classification(float) after few seconds app get crash

**Comment by the-dagger** [comment]
Hi, could you also tell us the amount of RAM in your device?

**Comment by onlymnsh** [comment]
> Hi, could you also tell us the amount of RAM in your device?

Yea, my device RAM is 2GB.

**Comment by the-dagger** [comment]
Hm, that might explain this.
@samtstern can we add `android:largeHeap="true"` to our MLKit sample's Manifest?

Here's an extract from google on this; 

> However, the ability to request a large heap is intended only for a small set of apps that can justify the need to consume more RAM (such as a large photo editing app). 

I think that the Photo Editing part coincides with our needs here.

@onlymnsh can you also try this? 
Set `android:largeHeap="true"` to your `application` tag in the manifest and see if the app still crashes?

**Comment by onlymnsh** [comment]
> Hm, that might explain this.
> @samtstern can we add `android:largeHeap="true"` to our MLKit sample's Manifest?
> 
> Here's an extract from google on this;
> 
> > However, the ability to request a large heap is intended only for a small set of apps that can justify the need to consume more RAM (such as a large photo editing app).
> 
> I think that the Photo Editing part coincides with our needs here.
> 
> @onlymnsh can you also try this?
> Set `android:largeHeap="true"` to your `application` tag in the manifest and see if the app still crashes?

I set android:largeHeap="true" but still same issue.

**Comment by 544531645** [comment]
I also happend oom

**Comment by samtstern** [comment]
I am going to track this in #842
