### ISSUE TITLE
java.lang.RuntimeException: Unable to get provider com.google.firebase.provider.FirebaseInitProvider: java.lang.NullPointerException: null reference

### ISSUE THREAD

**Issue by AlexNarbut** [firebase/quickstart-android#804]
Mobile - Samsung A9 (android version 8.0.0)
androidBuildToolsVersion = "28.0.3"
androidMinSdkVersion = 21
androidTargetSdkVersion = 28
androidCompileSdkVersion = 28

Hello, I try to start Firebase Messaging, but receive next exception

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: 'ru.example.app1, PID: 13186
    java.lang.RuntimeException: Unable to get provider com.google.firebase.provider.FirebaseInitProvider: java.lang.NullPointerException: null reference
        at android.app.ActivityThread.installProvider(ActivityThread.java:6581)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6133)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6043)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1764)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6942)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
     Caused by: java.lang.NullPointerException: null reference
        at com.google.android.gms.common.internal.Preconditions.checkNotNull(Unknown Source:2)
        at com.google.firebase.analytics.connector.AnalyticsConnectorImpl.getInstance(Unknown Source:9)
        at com.google.firebase.analytics.connector.internal.zzb.create(Unknown Source:6)
        at com.google.firebase.components.zzj.zza(com.google.firebase:firebase-common@@16.0.2:43)
        at com.google.firebase.components.zzk.get(Unknown Source:4)
        at com.google.firebase.components.zzj.get(com.google.firebase:firebase-common@@16.0.2:54)
        at com.google.firebase.components.zza.get(com.google.firebase:firebase-common@@16.0.2:26)
        at com.google.firebase.components.zzf.get(com.google.firebase:firebase-common@@16.0.2:34)
        at com.google.firebase.components.zzf.zza(com.google.firebase:firebase-common@@16.0.2:82)
        at com.google.firebase.FirebaseApp.zze(com.google.firebase:firebase-common@@16.0.2:761)
        at com.google.firebase.FirebaseApp.initializeApp(com.google.firebase:firebase-common@@16.0.2:359)
        at com.google.firebase.FirebaseApp.initializeApp(com.google.firebase:firebase-common@@16.0.2:324)
        at com.google.firebase.FirebaseApp.initializeApp(com.google.firebase:firebase-common@@16.0.2:310)
        at com.google.firebase.provider.FirebaseInitProvider.onCreate(com.google.firebase:firebase-common@@16.0.2:53)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1927)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1902)
        at com.google.firebase.provider.FirebaseInitProvider.attachInfo(com.google.firebase:firebase-common@@16.0.2:47)
        at android.app.ActivityThread.installProvider(ActivityThread.java:6578)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6133) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6043) 
        at android.app.ActivityThread.-wrap1(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1764) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6942) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374) 
```

**build.gradle in app module**
```groovy
apply plugin: 'com.android.application'

android {
    def globalConfiguration = rootProject.extensions.getByName("ext")

    compileSdkVersion globalConfiguration["androidCompileSdkVersion"]
    buildToolsVersion globalConfiguration["androidBuildToolsVersion"]
    defaultConfig {
        minSdkVersion globalConfiguration["androidMinSdkVersion"]
        targetSdkVersion globalConfiguration["androidTargetSdkVersion"]

        applicationId globalConfiguration["androidApplicationId"]
        versionCode globalConfiguration["androidVersionCode"]
        versionName globalConfiguration["androidVersionName"]

        testInstrumentationRunner globalConfiguration["testInstrumentationRunner"]
        testApplicationId globalConfiguration["testApplicationId"]

        vectorDrawables.useSupportLibrary = true
        javaCompileOptions {
            annotationProcessorOptions {
                includeCompileClasspath true
            }
        }
        multiDexEnabled true
    }
    buildTypes {
        debug {
            minifyEnabled false
            useProguard false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }

        release {
            minifyEnabled true
            useProguard true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    packagingOptions {
        exclude 'META-INF/rxjava.properties'
        exclude 'META-INF/DEPENDENCIES.txt'
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/NOTICE.txt'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/DEPENDENCIES'
        exclude 'META-INF/notice.txt'
        exclude 'META-INF/license.txt'
        exclude 'META-INF/dependencies.txt'
        exclude 'META-INF/LGPL2.1'
    }
}

configurations {
    implementation {
        exclude group: 'com.android.support', module: 'support-v4'
    }
}

repositories {
    maven {url "https://clojars.org/repo/"}
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')

    implementation project(path: ':domain')
    implementation project(path: ':data')
    implementation project(path: ':blecontrol')
    implementation project(':apputils')

    def androidDependencies = rootProject.ext.androidDependencies
    def developmentDependencies = rootProject.ext.developmentDependencies

    //Android
    implementation androidDependencies.appCompat
    implementation androidDependencies.supportDesign
    implementation androidDependencies.cardView
    implementation androidDependencies.constraint
    //moxy
    implementation androidDependencies.moxy
    compileOnly androidDependencies.moxyProcessor
    implementation androidDependencies.moxyBaseView
    implementation androidDependencies.moxyAppCompat

    //rxJava
    implementation androidDependencies.rxJava
    implementation androidDependencies.rxAndroid
    implementation androidDependencies.rxBinding
    implementation androidDependencies.rxBindingAppV7

    implementation androidDependencies.gson

    implementation androidDependencies.multiDex

    //dagger
    annotationProcessor androidDependencies.daggerCompiler
    implementation androidDependencies.dagger
    //butterKnife
    implementation androidDependencies.butterKnife
    annotationProcessor  androidDependencies.butterKnifeCompiler

    //glide
    implementation androidDependencies.glide
    annotationProcessor androidDependencies.glideProcessor

    //lombok
    compileOnly androidDependencies.lombok

    //nordic
    compileOnly androidDependencies.nordicScan

    //icepick
    implementation androidDependencies.icepick
    compileOnly androidDependencies.icepickProcessor

    //map
    implementation 'org.osmdroid:osmdroid-android:6.0.1'

    //ui
    implementation androidDependencies.rxpermissions

    //fcm
    implementation 'com.google.firebase:firebase-core:16.0.7'
    implementation 'com.google.firebase:firebase-messaging:17.3.4'


    implementation 'de.hdodenhof:circleimageview:2.2.0'
    implementation 'com.daasuu:animateHorizontalProgressBar:0.2.4'
    implementation ('com.github.ozodrukh:CircularReveal:2.0.1@aar') {
        transitive = true;
    }
    implementation 'com.mikepenz:itemanimators:1.0.2@aar'
    implementation 'me.zhanghai.android.materialratingbar:library:1.3.1'
    implementation 'com.github.chrisbanes:PhotoView:2.3.0'

    implementation 'com.github.castorflex.smoothprogressbar:library:1.1.0'
    implementation 'com.andrognito.flashbar:flashbar:1.0.3'

    implementation 'com.github.doctoror.particlesdrawable:library:1.0.9'

    implementation 'com.facebook.shimmer:shimmer:0.4.0'

    //pdf
    implementation 'com.github.barteksc:android-pdf-viewer:2.8.2'

    //development
    implementation developmentDependencies.leakCanary
}

apply plugin: 'com.google.gms.google-services'
```

**build.gradle in project** 
```groovy
apply from: 'gbuild/dependencies.gradle'
buildscript {

    repositories {
        jcenter()
        mavenCentral()
        maven { url = "https://oss.sonatype.org/content/repositories/snapshots/" }
        google()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.3.1'
        classpath 'io.realm:realm-gradle-plugin:5.7.1'
        classpath 'com.google.gms:google-services:4.2.0' // google-services plugin
    }
}

allprojects {
    repositories {
        jcenter()
        mavenCentral()
        maven { url "https://jitpack.io" }
        google()
    }

    ext {
        androidApplicationId = 'ru.example.app1'
        androidVersionCode = 9
        androidVersionName = "1.8"
        testInstrumentationRunner = "android.support.test.runner.AndroidJUnitRunner"
        testApplicationId = ''ru.example.app1.test'
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

**Comment by samtstern** [comment]
@AlexNarbut there is a *lot* to see here and it would be nearly impossible for us to sort out the cause of this issue from all of that build configuration.  I am almost positive this is a build issue particular to your app so you should ask for help on a forum better suited to general debugging, like StackOverflow.

If you can reproduce this issue with one of the sample apps in this repo (either as-is or with minimal changes) please let me know and I will re-open for discussion.

**Comment by iTheDaybreak** [comment]
I run into this issue too:

03-22 00:39:49.595  2002  2002 E AndroidRuntime: java.lang.RuntimeException: Unable to get provider com.google.firebase.provider.FirebaseInitProvider: java.lang.NullPointerException: null reference
03-22 00:39:49.595  2002  2002 E AndroidRuntime: 	at android.app.ActivityThread.installProvider(ActivityThread.java:6435)
03-22 00:39:49.595  2002  2002 E AndroidRuntime: 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:5977)
03-22 00:39:49.595  2002  2002 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5892)
03-22 00:39:49.595  2002  2002 E AndroidRuntime: 	at android.app.ActivityThread.access$1200(ActivityThread.java:207)
03-22 00:39:49.595  2002  2002 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1679)
03-22 00:39:49.595  2002  2002 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
03-22 00:39:49.595  2002  2002 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
03-22 00:39:49.595  2002  2002 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6710)
03-22 00:39:49.595  2002  2002 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-22 00:39:49.595  2002  2002 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
03-22 00:39:49.595  2002  2002 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911)
03-22 00:39:49.595  2002  2002 E AndroidRuntime: Caused by: java.lang.NullPointerException: null reference
03-22 00:39:49.595  2002  2002 E AndroidRuntime: 	at com.google.android.gms.common.internal.p.a(Unknown Source:2)
03-22 00:39:49.595  2002  2002 E AndroidRuntime: 	at com.google.firebase.analytics.connector.b.a(Unknown Source:9)
03-22 00:39:49.595  2002  2002 E AndroidRuntime: 	at com.google.firebase.analytics.connector.internal.a.a(Unknown Source:6)
03-22 00:39:49.595  2002  2002 E AndroidRuntime: 	at com.google.firebase.components.q.a(com.google.firebase:firebase-common@@16.0.2:43)
03-22 00:39:49.595  2002  2002 E AndroidRuntime: 	at com.google.firebase.components.r.a(Unknown Source:4)
03-22 00:39:49.595  2002  2002 E AndroidRuntime: 	at com.google.firebase.components.q.a(com.google.firebase:firebase-common@@16.0.2:54)
03-22 00:39:49.595  2002  2002 E AndroidRuntime: 	at com.google.firebase.components.i.a(com.google.firebase:firebase-common@@16.0.2:26)
03-22 00:39:49.595  2002  2002 E AndroidRuntime: 	at com.google.firebase.components.m.a(com.google.firebase:firebase-common@@16.0.2:34)
03-22 00:39:49.595  2002  2002 E AndroidRuntime: 	at com.google.firebase.components.m.a(com.google.firebase:firebase-common@@16.0.2:82)
03-22 00:39:49.595  2002  2002 E AndroidRuntime: 	at com.google.firebase.b.j(com.google.firebase:firebase-common@@16.0.2:761)
03-22 00:39:49.595  2002  2002 E AndroidRuntime: 	at com.google.firebase.b.a(com.google.firebase:firebase-common@@16.0.2:359)
03-22 00:39:49.595  2002  2002 E AndroidRuntime: 	at com.google.firebase.b.a(com.google.firebase:firebase-common@@16.0.2:324)
03-22 00:39:49.595  2002  2002 E AndroidRuntime: 	at com.google.firebase.b.a(com.google.firebase:firebase-common@@16.0.2:310)
03-22 00:39:49.595  2002  2002 E AndroidRuntime: 	at com.google.firebase.provider.FirebaseInitProvider.onCreate(com.google.firebase:firebase-common@@16.0.2:53)
03-22 00:39:49.595  2002  2002 E AndroidRuntime: 	at android.content.ContentProvider.attachInfo(ContentProvider.java:1919)
03-22 00:39:49.595  2002  2002 E AndroidRuntime: 	at android.content.ContentProvider.attachInfo(ContentProvider.java:1894)
03-22 00:39:49.595  2002  2002 E AndroidRuntime: 	at com.google.firebase.provider.FirebaseInitProvider.attachInfo(com.google.firebase:firebase-common@@16.0.2:47)
03-22 00:39:49.595  2002  2002 E AndroidRuntime: 	at android.app.ActivityThread.installProvider(ActivityThread.java:6430)
03-22 00:39:49.595  2002  2002 E AndroidRuntime: 	... 10 more

**Comment by kitenium** [comment]
Same issue here:

    --------- beginning of crash
2019-05-21 09:49:05.235 5043-5043/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.trimble.workzone, PID: 5043
    java.lang.RuntimeException: Unable to get provider com.google.firebase.provider.FirebaseInitProvider: com.google.firebase.components.MissingDependencyException: Unsatisfied dependency for component Component<[class com.google.firebase.inappmessaging.display.FirebaseInAppMessagingDisplay]>{2, type=0, deps=[Dependency{anInterface=interface com.google.firebase.analytics.connector.AnalyticsConnector, type=required, direct=true}, Dependency{anInterface=class com.google.firebase.FirebaseApp, type=required, direct=true}, Dependency{anInterface=class com.google.firebase.inappmessaging.FirebaseInAppMessaging, type=required, direct=true}]}: interface com.google.firebase.analytics.connector.AnalyticsConnector
        at android.app.ActivityThread.installProvider(ActivityThread.java:6288)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:5851)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5772)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1661)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
     Caused by: com.google.firebase.components.MissingDependencyException: Unsatisfied dependency for component Component<[class com.google.firebase.inappmessaging.display.FirebaseInAppMessagingDisplay]>{2, type=0, deps=[Dependency{anInterface=interface com.google.firebase.analytics.connector.AnalyticsConnector, type=required, direct=true}, Dependency{anInterface=class com.google.firebase.FirebaseApp, type=required, direct=true}, Dependency{anInterface=class com.google.firebase.inappmessaging.FirebaseInAppMessaging, type=required, direct=true}]}: interface com.google.firebase.analytics.connector.AnalyticsConnector
        at com.google.firebase.components.ComponentRuntime.validateDependencies(com.google.firebase:firebase-common@@17.0.0:167)
        at com.google.firebase.components.ComponentRuntime.processInstanceComponents(com.google.firebase:firebase-common@@17.0.0:86)
        at com.google.firebase.components.ComponentRuntime.<init>(com.google.firebase:firebase-common@@17.0.0:70)
        at com.google.firebase.FirebaseApp.<init>(com.google.firebase:firebase-common@@17.0.0:478)
        at com.google.firebase.FirebaseApp.initializeApp(com.google.firebase:firebase-common@@17.0.0:354)
        at com.google.firebase.FirebaseApp.initializeApp(com.google.firebase:firebase-common@@17.0.0:321)
        at com.google.firebase.FirebaseApp.initializeApp(com.google.firebase:firebase-common@@17.0.0:305)
        at com.google.firebase.provider.FirebaseInitProvider.onCreate(com.google.firebase:firebase-common@@17.0.0:53)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1919)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1894)
        at com.google.firebase.provider.FirebaseInitProvider.attachInfo(com.google.firebase:firebase-common@@17.0.0:47)
        at android.app.ActivityThread.installProvider(ActivityThread.java:6285)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:5851) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5772) 
        at android.app.ActivityThread.-wrap1(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1661) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6541) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**Comment by girubhai** [comment]
Any solution ?

java.lang.RuntimeException: Unable to get provider com.google.firebase.provider.FirebaseInitProvider: java.lang.NullPointerException: null reference
	at android.app.ActivityThread.installProvider(ActivityThread.java:7181)
	at android.app.ActivityThread.installContentProviders(ActivityThread.java:6659)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6576)
	at android.app.ActivityThread.access$1500(ActivityThread.java:230)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1911)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7551)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)
Caused by: java.lang.NullPointerException: null reference
	at com.google.android.gms.common.internal.Preconditions.checkNotNull(Unknown Source:2)
	at com.google.firebase.analytics.connector.AnalyticsConnectorImpl.getInstance(com.google.android.gms:play-services-measurement-api@@18.0.0:9)
	at com.google.firebase.analytics.connector.internal.zzb.create(com.google.android.gms:play-services-measurement-api@@18.0.0:6)
	at com.google.firebase.components.ComponentRuntime.lambda$new$0(ComponentRuntime.java:72)
	at com.google.firebase.components.ComponentRuntime$$Lambda$1.get(Unknown Source:4)
	at com.google.firebase.components.Lazy.get(Lazy.java:53)
	at com.google.firebase.components.ComponentRuntime.initializeEagerComponents(ComponentRuntime.java:161)
	at com.google.firebase.FirebaseApp.initializeAllApis(FirebaseApp.java:583)
	at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:302)
	at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:266)
	at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:251)
	at com.google.firebase.provider.FirebaseInitProvider.onCreate(FirebaseInitProvider.java:51)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:2118)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:2092)
	at com.google.firebase.provider.FirebaseInitProvider.attachInfo(FirebaseInitProvider.java:45)
	at android.app.ActivityThread.installProvider(ActivityThread.java:7176)
	... 10 more
