### ISSUE TITLE
Using ML Kit on ASUS phone can't download model

### ISSUE THREAD

**Issue by filghk** [firebase/quickstart-android#805]
### Step 1: Describe your environment

  * Android device: ASUS_X00RD
  * Android OS version: 8.1.0
  * Google Play Services version: 
  * Firebase/Play Services SDK version: Firebase ml-vision:19.0.2/Play Services 15.0.90(110306-231259764) 
  
### Step 2: Describe the problem:

	This phone cannot download the model no matter how many times it is triggered.
	I can't download it when I restore my phone.
	Other brands are currently in perfect use.
    
#### Observed Results:

  com.google.android.gms.dynamite.DynamiteModule$LoadingException: No acceptable module found. Local version is 0 and remote version is 0.
        at com.google.android.gms.dynamite.DynamiteModule.load(Unknown Source:8)
        at com.google.android.gms.internal.vision.zzm.zzq(Unknown Source:28)
        at com.google.android.gms.internal.vision.zzm.isOperational(Unknown Source:9)
        at com.google.android.gms.vision.barcode.BarcodeDetector.isOperational(Unknown Source:23)
        at com.google.android.gms.internal.firebase_ml.zzjl.zza(Unknown Source:23)
        at com.google.android.gms.internal.firebase_ml.zzjl.zza(Unknown Source:42)
        at com.google.android.gms.internal.firebase_ml.zzij.call(Unknown Source:3)
        at com.google.android.gms.internal.firebase_ml.zzie.zza(Unknown Source:29)
        at com.google.android.gms.internal.firebase_ml.zzif.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.google.android.gms.internal.firebase_ml.zze.dispatchMessage(Unknown Source:6)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)
2019-02-15 08:55:52.810 3546-3546/? E/BarcodeScanProc: Barcode detection failed com.google.firebase.ml.common.FirebaseMLException: Waiting for the barcode detection model to be downloaded. Please wait.
  
#### Expected Results:

How do I use it on my ASUS phone?

**Comment by samtstern** [comment]
@flighk I see this message in your logs:

```
com.google.android.gms.dynamite.DynamiteModule$LoadingException: No acceptable module found. Local version is 0 and remote version is 0.
```

This implies that your phone does not have a recent version of Google Play services.  Are you signed in with a google account on the phone?  If so can you check (in Setttings > Applications) what the version of Google Play services is?

**Comment by filghk** [comment]
Hello
I have a Google Account login
I have provided
* Google Play Services version: 13.4.11-all [0] [PR] 231519563
* Play Services 15.0.90（110306-231259764）
I clicked and told me that it is the latest version.

I have tested and joined the Play services tester.
Some of my phones need to join the tester to use ML Kit.
ASUS mobile phone testers can not use the ML Kit.

**Comment by khahmad** [comment]
i have the same issue did u find a solution

**Comment by samtstern** [comment]
@filghk `15.0.90` is indeed the latest version, but where are you seeing `13.4.11-all`?  Can you maybe provide a screenshot for that?

**Comment by filghk** [comment]
PLAY(APP)-Settings
The screenshot is my phone.
I have returned my colleagues to the ASUS phone.
The app I wrote is for the company.
So I can get a lot of different phone tests.
Most of them can be used by simply updating the Play Services and PLAY stores.
Only a small part like this Asus phone can't be used.

@khahmad
Provide a way for you
In my many tested machines
Some are due to the capacity is too low to download the model failed
A capacity below 1GB will generally fail
The mobile phone capacity given by our company is very small
Most of my processing is for this reason

![play1](https://user-images.githubusercontent.com/29191794/53058951-1d4ea700-34f0-11e9-80bf-c5da7fd703da.png)
![play2](https://user-images.githubusercontent.com/29191794/53058952-1d4ea700-34f0-11e9-9920-f73389b3d975.png)

**Comment by khahmad** [comment]
Hello @filghk  i use a devices for testing using by all my company, the apps was worked fine before the new update of google play service(15.0.90(110306-231259764), i tried to do a factory reset to the devices and check the free space (11 Gb free space),
i tried to install the app to my personal devices it is worked fine with google play service(15.0.90(040408..), also i triedd with other devices with the same version of google play service of testing device(15.0.90(110306-231259764) but it is not working so the problem is with the google play service(110306-231259764) if anyone has a solution for this please reply ASAP

**Comment by samtstern** [comment]
@filghk it does seem like you have all the right versions here ... to be honest I am not sure what is failing here.  I will have to ask around

**Comment by foozeNZ** [comment]
I have the same issue with both this sample and the older vision sample. (See issue post here: https://github.com/googlesamples/android-vision/issues/408 ). Tried all the same fixes (make sure things are updated, clearing cache, even a factory reset).

My best theory at this stage is it's something to do with Android "Go". I can't reproduce the problem on anything other than our Vodafone N9 lite, which is Android "Go" edition (others are not). Only happens with the barcode detection part of this app, other recognition is fine. 
The older vision sample (and our app that uses it) used to work fine, we got the first reported problem on the 7th of Feb 2019.


Phone: Vodafone N9 Lite
Android ver: 8.1.0 - Android Go
Play services version: 15.0.90 (110304-231259764)

`02-26 09:20:51.395 25412-25453/com.google.firebase.samples.apps.mlkit E/BarcodeNativeHandle: Error Loading module
    com.google.android.gms.dynamite.DynamiteModule$LoadingException: No acceptable module found. Local version is 0 and remote version is 0.
        at com.google.android.gms.dynamite.DynamiteModule.load(Unknown Source:8)
        at com.google.android.gms.internal.vision.zzm.zzq(Unknown Source:28)
        at com.google.android.gms.internal.vision.zzm.isOperational(Unknown Source:9)
        at com.google.android.gms.vision.barcode.BarcodeDetector.isOperational(Unknown Source:23)
        at com.google.android.gms.internal.firebase_ml.zzoj.zza(Unknown Source:23)
        at com.google.android.gms.internal.firebase_ml.zzoj.zza(Unknown Source:42)
        at com.google.android.gms.internal.firebase_ml.zznd.call(Unknown Source:4)
        at com.google.android.gms.internal.firebase_ml.zzmy.zza(Unknown Source:29)
        at com.google.android.gms.internal.firebase_ml.zzmz.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.google.android.gms.internal.firebase_ml.zze.dispatchMessage(Unknown Source:6)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)
02-26 09:20:51.409 25412-25412/com.google.firebase.samples.apps.mlkit E/BarcodeScanProc: Barcode detection failed com.google.firebase.ml.common.FirebaseMLException: Waiting for the barcode detection model to be downloaded. Please wait.`

You can wait all you want, but nothing happens...

**Comment by filghk** [comment]
ASUS_X00RD checked for Android Go
![go](https://user-images.githubusercontent.com/29191794/53386613-e419a980-39bd-11e9-9825-d07116126b33.png)

**Comment by Riaan-Crause-Kohde** [comment]
@foozeNZ I think you might be onto something. The only device I'm getting this on is running Android Go (Adding it so the Firebase team have more info).

Phone: Samsung Galaxy J2 Core
Android ver: 8.1.0 - Android Go
Play services version: 16.0.89 (110304-239467275)

**Comment by GianfrancoMS** [comment]
I'm also having this issue on Android Go phones.

**Comment by mic-** [comment]
@foozeNZ I've seen the same logs on Moto E5 Play running Android 8.1.0 Go / Google Play Services 16.0.91 (except that I'm using GMS Vision rather than ML Kit).

The only way I've been able to fix it is by deactivating Google Play Services in the app manager and downgrading to an older version (12.8.76) when being asked if I wanted to do so, and then activating Google Play Services again.

Downloading the barcode library worked after that. However, if I upgraded to 16.0.91 again even after having downloaded the barcode library successfully, it stopped working again. Barcode scanning with version 16.0.91 works just fine on a Galaxy S7 running Android 7.0 though, so there's something about this combination of Android version and Google Player Services version.

**Comment by dannevesdantas** [comment]
I'm facing exactly the same issue @mic- described, also a moto e5 play running Android 8.1.0 Go and Google Play Services 16.0.91

**Comment by gjsalot** [comment]
Same issue as well on Nexus One (8.1.0 Go).

**Comment by lucasviveiros** [comment]
Same issue as well on...

 **- Describe your environment**
Android device: SAMSUNG GALAXY J4 CORE
Android OS version: 8.1.0 Go
Google Play Services version: 17.7.85

**Comment by multiprecision** [comment]
Having the same issue on:
```
    Android device: XiaoMi Redmi Go
    Android version: 8.1.0 Go
    Google Play services version: 17.7.85 (110306-253824076)
    Firebase version: firebase-ml-vision 22.0.0
```

**Comment by multiprecision** [comment]
Having the same issue on:
```
    Android device: XiaoMi Redmi Go
    Android version: 8.1.0 Go
    Google Play services version: 17.7.85 (110306-253824076)
    Firebase version: firebase-ml-vision 22.0.0
```
Only the barcode scanner doesn't work. The others work.

**Comment by jogiji** [comment]
Similar issue with Telpo TPS 900..Barcode scanning fails

**Comment by meJevin** [comment]
This is a real issue. Can we please get some help here?

**Comment by jogiji** [comment]
This issue still exists on my device even with latest Play Services beta

**Comment by mic-** [comment]
I've re-tested this quickly on a Nokia 1 and a Moto e5 Play - both of which have had trouble downloading the barcode library in the past - and it appears to be working with the latest Google Play Services version (18.7.something). I'll probably have to test some more before I say anything conclusively, but it looks promising so far.

**Comment by Tougee** [comment]
If there any API can check these dependencies not available

**Comment by klaszlo8207** [comment]
Any Fix for this? Same thing for Huawei Mate 20 PRO

 Error loading module com.google.android.gms.vision.ocr optional module true: com.google.android.gms.dynamite.DynamiteModule$LoadingException: No acceptable module found. Local version is 0 and remote version is 0.

**Comment by TonyZhang19950601** [comment]
Have same issue on download ocr models. I found that sometimes the ocr_start file will not be deleted after the ocr model has been successfully downloaded by GMS. In that case, the model status will always be downloading even if the model has already been downloaded into com.google.android.

**Comment by Freakadroid** [comment]
I have the same issue, two devices with Android 7.1.1 and 7.1.2
Google play services 20.06.16
Using
implementation 'com.google.firebase:firebase-ml-vision:24.0.1'
classpath 'com.google.gms:google-services:4.3.3'

It's been a month researching and no clues. I think it's an Android thing.
I have a release date on March 20th and I am going to fail because of GOOGLE, not some cheap library no one uses.
This is ridiculous. The models never download, Iis there anyone looking into this?

**Comment by msxenon** [comment]
Same issue mlkit on my app works on my phone only , not in the emulators or in my testers phones

**Comment by cs-googler** [comment]
> I have the same issue, two devices with Android 7.1.1 and 7.1.2
> Google play services 20.06.16
> Using
> implementation 'com.google.firebase:firebase-ml-vision:24.0.1'
> classpath 'com.google.gms:google-services:4.3.3'
> 
> It's been a month researching and no clues. I think it's an Android thing.
> I have a release date on March 20th and I am going to fail because of GOOGLE, not some cheap library no one uses.
> This is ridiculous. The models never download, Iis there anyone looking into this?

Hi, sorry about your frustration. To understand more about what is happening, **could you send some bug reports to this email address: songchenxi@google.com?**

Also, we have identified a bug earlier with module downloading which requires a reboot of the device sometimes to get recovered. The fix will be available in the next GMSCore release. See details here: https://buganizer.corp.google.com/issues/149273821

**Comment by cs-googler** [comment]
> Any Fix for this? Same thing for Huawei Mate 20 PRO
> 
> I need to use ocr/text recognition
> 
> Error loading module com.google.android.gms.vision.ocr optional module true: com.google.android.gms.dynamite.DynamiteModule$LoadingException: No acceptable module found. Local version is 0 and remote version is 0.
> 
> **google play store version 18.8.16-all**

Hi, you will need to update your google play store version as the module download is only supported for the most recent gmscore versions. Currently, the earliest version we support is 19.8.31. There might be some reasons that your device was not getting automatically updated to the latest versions.
Once you update your gmscore to the latest version, note that we have identified a bug earlier with module downloading which requires a reboot of the device sometimes to get recovered. The fix will be available in the next GMSCore release. See details here: https://buganizer.corp.google.com/issues/149273821

**Comment by octopus22** [comment]
I am having the same issue as this with OCR. 

When I uninstall my android app clear the Google Play Services' data to remove Firebase modules and reinstall my app this issue occurs. The only way to fix this issue is to restart my device and run the android app again. 

Google Play Services: 20.09.14
Android: 9.0.6

**Comment by cs-googler** [comment]
> I am having the same issue as this with OCR.
> 
> When I uninstall my android app clear the Google Play Services' data to remove Firebase modules and reinstall my app this issue occurs. The only way to fix this issue is to restart my device and run the android app again.
> 
> Google Play Services: 20.09.14
> Android: 9.0.6

Hi, we have identified a bug earlier with module downloading which requires a reboot of the device sometimes to get recovered(specifically when the gmscore version got updated recently). The fix will be available in the next GMSCore release.

**Comment by octopus22** [comment]
Thank you for your response,

Sorry I am new to android development, does this mean the issue is related
to an android update? As In does GMScore automatically update when it is
released to android?

Thank you

**Comment by beersheba** [comment]
Having the same issue on Xiaomi MI 8 SE.

```
2020-06-23 18:01:02.165 14211-14553/com.google.codelab.mlkit E/Vision: Error loading module com.google.android.gms.vision.ocr optional module true: com.google.android.gms.dynamite.DynamiteModule$LoadingException: No acceptable module found. Local version is 0 and remote version is 0.
2020-06-23 18:01:02.166 14211-14553/com.google.codelab.mlkit W/e.codelab.mlki: Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
2020-06-23 18:01:02.168 14211-14211/com.google.codelab.mlkit W/System.err: com.google.mlkit.common.MlKitException: Waiting for the text recognition model to be downloaded. Please wait.
```

Play Store version: 20.4.18
Google Play Services 20.21.17
