### ISSUE TITLE
Androidx Google sign in method 

### ISSUE THREAD

**Issue by oussemaAr** [firebase/quickstart-android#807]
### Step 1: Describe your environment

  * Android device: Asus Zenfone
  * Android OS version: 6.0.0
  * Google Play Services version: 4.2.0
  * Firebase/Play Services SDK version: 16.0.6
  
### Step 2: Describe the problem:
The application crashes after migrating to androidX
#### Observed Results:

  Caused by: java.lang.NullPointerException: Attempt to read from field 'androidx.fragment.app.FragmentController androidx.fragment.app.FragmentActivity.mFragments' on a null object reference
        at androidx.fragment.app.FragmentActivity.onRequestPermissionsResult(FragmentActivity.java:845)
        at androidx.lifecycle.LiveData.observe(LiveData.java:172)
        at androidx.loader.app.LoaderManagerImpl$LoaderInfo.setCallback(LoaderManagerImpl.java:100)
        at androidx.loader.app.LoaderManagerImpl.createAndInstallLoader(LoaderManagerImpl.java:400)
        at androidx.loader.app.LoaderManagerImpl.initLoader(LoaderManagerImpl.java:421)
        at com.google.android.gms.auth.api.signin.internal.SignInHubActivity.zzn(Unknown Source)
        at com.google.android.gms.auth.api.signin.internal.SignInHubActivity.onActivityResult(Unknown Source)
        at android.app.Activity.dispatchActivityResult(Activity.java:6528)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:3713)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:3760) 
        at android.app.ActivityThread.access$1400(ActivityThread.java:153) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1396) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.app.ActivityThread.main(ActivityThread.java:5451) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
  
#### Expected Results:

  Expected to sign in using selected gmail account
  
#### Relevant Code:

  ```
  public static GoogleApiClient createGoogleApiClient(FragmentActivity fragmentActivity) {
        GoogleApiClient.OnConnectionFailedListener failedListener;

        if (fragmentActivity instanceof GoogleApiClient.OnConnectionFailedListener) {
            failedListener = (GoogleApiClient.OnConnectionFailedListener) fragmentActivity;
        } else {
            throw new IllegalArgumentException(fragmentActivity.getClass().getSimpleName() + " should implement OnConnectionFailedListener");
        }

        GoogleSignInOptions gso = new GoogleSignInOptions.Builder(GoogleSignInOptions.DEFAULT_SIGN_IN)
                .requestIdToken(fragmentActivity.getResources().getString(R.string.google_web_client_id))
                .requestEmail()
                .build();

        return new GoogleApiClient.Builder(fragmentActivity)
                .enableAutoManage(fragmentActivity, failedListener)
                .addApi(Auth.GOOGLE_SIGN_IN_API, gso)
                .build();
    }

public void connect(){
    mGoogleApiClient = createGoogleApiClient(this);
    Intent signInIntent = Auth.GoogleSignInApi.getSignInIntent(mGoogleApiClient);
    startActivityForResult(signInIntent, SIGN_IN_GOOGLE);
}
  ```

**Comment by samtstern** [comment]
@oussemaAr this doesn't seem to be an issue with Firebase or an issue with the sample code in this repo (we have not updated to AndroidX yet, but we should!).  You should ask this question on StackOverflow where someone can help you debug your AndroidX issue.
