### ISSUE TITLE
Fatal Exception: java.lang.RuntimeException: Error receiving broadcast Intent

### ISSUE THREAD

**Issue by okq91** [firebase/quickstart-android#827]
* Android device: Various devices  
  * Android OS version: 4,5,6,7
  * Google Play Services version: 3.0.0
  * Firebase/Play Services SDK version: 12.0.1
  
    implementation 'com.google.android.gms:play-services-analytics:12.0.1'
    implementation 'com.google.android.gms:play-services-ads:12.0.1'
    implementation 'com.google.android.gms:play-services-auth:12.0.1'
    implementation 'com.google.firebase:firebase-core:12.0.1'
    implementation 'com.google.firebase:firebase-database:12.0.1'
    implementation 'com.google.firebase:firebase-auth:12.0.1'
    implementation 'com.google.firebase:firebase-storage:12.0.1'
    implementation 'com.google.firebase:firebase-messaging:12.0.1'
    implementation 'com.google.firebase:firebase-invites:12.0.1'
    implementation 'com.google.firebase:firebase-perf:12.0.1'

 The app is keep crashing on various range of devices and OS versions,

Crash on Fabric:
LoadedApk.java line 662
android.app.LoadedApk.forgetReceiverDispatcher

*note that the same crash appears in different lines in LoadedApk.java

Fatal Exception: java.lang.RuntimeException: Error receiving broadcast Intent { act=android.net.conn.CONNECTIVITY_CHANGE flg=0x8000010 (has extras) } in com.google.firebase.iid.e@4207f700
       at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:773)
       at android.os.Handler.handleCallback(Handler.java:725)
       at android.os.Handler.dispatchMessage(Handler.java:92)
       at android.os.Looper.loop(Looper.java:176)
       at android.app.ActivityThread.main(ActivityThread.java:5319)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
       at dalvik.system.NativeStart.main(NativeStart.java)

Caused by java.lang.IllegalArgumentException: Receiver not registered: com.google.firebase.iid.e@4207f700
       at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:662)
       at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1702)
       at com.google.firebase.iid.zzad.onReceive(Unknown Source)
       at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:763)
       at android.os.Handler.handleCallback(Handler.java:725)
       at android.os.Handler.dispatchMessage(Handler.java:92)
       at android.os.Looper.loop(Looper.java:176)
       at android.app.ActivityThread.main(ActivityThread.java:5319)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
       at dalvik.system.NativeStart.main(NativeStart.java)

I have tried to reproduce this issue on different OS versions and devices, by connect/disconnect network while using the application but unable to reproduce it.

**Comment by samtstern** [comment]
@okq91 version `12.0.1` is about a year old, have you considered updating? 

Also this looks to be the same as this public issue:
https://issuetracker.google.com/36926781

**Comment by okq91** [comment]
@samtstern Do you think that upgrade Firebase version would solve this issue and witch version contains fix for it?

**Comment by samtstern** [comment]
@okq91 that's just a guess, but if you could try upgrading `analytics`, `ads`, `core`, `messaging` and `perf` to the latest version  you would pick up a lot of bugfixes.

**Comment by okq91** [comment]
Thank you this issue has been fixed by upgrading Firebase libraries to the latest version.

**Comment by samtstern** [comment]
@okq91 thanks for confirming!

**Comment by shaz-tech** [comment]
Reproducable in the latest version.
firebase_base_version = '17.1.0'
firebase_messaging_version = '20.1.0'
firebase_analytics_version = '17.2.1'

Log: java.lang.RuntimeException: Error receiving broadcast Intent { act=android.net.conn.CONNECTIVITY_CHANGE flg=0x4000010 (has extras) } in com.google.firebase.iid.zzau@db3fb2c
        at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$-android_app_LoadedApk$ReceiverDispatcher$Args_52497(LoadedApk.java:1323)
        at android.app.-$Lambda$aS31cHIhRx41653CMnd4gZqshIQ.$m$7(Unknown Source:4)
        at android.app.-$Lambda$aS31cHIhRx41653CMnd4gZqshIQ.run(Unknown Source:39)

**Comment by TOPWN** [comment]
> Reproducable in the latest version.
> firebase_base_version = '17.1.0'
> firebase_messaging_version = '20.1.0'
> firebase_analytics_version = '17.2.1'
> 
> Log: java.lang.RuntimeException: Error receiving broadcast Intent { act=android.net.conn.CONNECTIVITY_CHANGE flg=0x4000010 (has extras) } in com.google.firebase.iid.zzau@db3fb2c
> at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$-android_app_LoadedApk$ReceiverDispatcher$Args_52497(LoadedApk.java:1323)
> at android.app.-$Lambda$aS31cHIhRx41653CMnd4gZqshIQ.$m$7(Unknown Source:4)
> at android.app.-$Lambda$aS31cHIhRx41653CMnd4gZqshIQ.run(Unknown Source:39)
> 
> > Caused by: java.lang.IllegalStateException: FirebaseApp was deleted

Same.
