### ISSUE TITLE
Arcore face crash

### ISSUE THREAD

**Issue by 544531645** [firebase/quickstart-android#833]
### Step 1: Describe your environment

  * Android device: __google pixel___
  * Android OS version: ___9.0__
  * Google Play Services version: ____4.1.0_
  * Firebase/Play Services SDK version: _____firebase-ml-vision:19.0.2
  
#### Steps to reproduce:

Arcore facial recognition tracking, flashback

#### Observed Results:

 Process: com.google.ar.sceneform.samples.augmentedfaces, PID: 11199
    java.lang.IllegalArgumentException: Invalid image data size.
        at com.google.android.gms.vision.Frame$Builder.setImageData(Unknown Source:13)
        at com.google.firebase.ml.vision.common.FirebaseVisionImage.zza(Unknown Source:137)
        at com.google.firebase.ml.vision.face.FirebaseVisionFaceDetector.detectInImage(Unknown Source:26)
        at com.google.ar.sceneform.samples.augmentedfaces.AugmentedFacesActivity.lambda$onCreate$1(AugmentedFacesActivity.java:180)  
#### Expected Results:

Be able to identify, do not crash back  
#### Relevant Code:
![image](https://user-images.githubusercontent.com/15622364/54331247-1bda4f80-4654-11e9-8c28-5a5f8cb14b31.png)

**Comment by samtstern** [comment]
Hmm the key here seems to be this call:
```
java.lang.IllegalArgumentException: Invalid image data size.
```
