### ISSUE TITLE
ML Kit:"Waiting for the text recognition model to be downloaded. Please wait" on Vuzix M300 Smart glasses

### ISSUE THREAD

**Issue by Shekharb694** [firebase/quickstart-android#861]
Android device: Vuzix M300 Smart Glasses
    Android OS version: Android 6.0.1 Api 23
    Google Play Services version: none
    Firebase/Play Services SDK version:
    All my dependency's
    // ML Kit dependencies
    implementation 'com.google.firebase:firebase-ml-vision:19.0.3'
    implementation 'com.google.firebase:firebase-ml-vision-image-label-model:17.0.2'
    implementation 'com.google.firebase:firebase-ml-vision-face-model:17.0.2'
    implementation 'com.google.firebase:firebase-ml-model-interpreter:18.0.0'

And classpath 'com.google.gms:google-services:4.2.0'

problem:
Text detection failed.com.google.firebase.ml.common.FirebaseMLException: Waiting for the text
recognition model to be downloaded. Please wait.

Stack Trace :
04-12 11:48:55.334 4586-4648/com.google.firebase.samples.apps.mlkit E/TextNativeHandle: Error Loading module
    com.google.android.gms.dynamite.DynamiteModule$LoadingException: No acceptable module found. Local version is 0 and remote version is 0.
        at com.google.android.gms.dynamite.DynamiteModule.load(Unknown Source)
        at com.google.android.gms.internal.vision.zzm.zzq(Unknown Source)
        at com.google.android.gms.internal.vision.zzak.<init>(Unknown Source)
        at com.google.android.gms.vision.text.TextRecognizer$Builder.build(Unknown Source)
        at com.google.android.gms.internal.firebase_ml.zzqj.zzlp(Unknown Source)
        at com.google.android.gms.internal.firebase_ml.zznx.zzf(Unknown Source)
        at com.google.android.gms.internal.firebase_ml.zznz.zzls(Unknown Source)
        at com.google.android.gms.internal.firebase_ml.zznz.call(Unknown Source)
        at com.google.android.gms.internal.firebase_ml.zznn.zza(Unknown Source)
        at com.google.android.gms.internal.firebase_ml.zzno.run(Unknown Source)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at com.google.android.gms.internal.firebase_ml.zzi.dispatchMessage(Unknown Source)
        at android.os.Looper.loop(Looper.java:148)
        at android.os.HandlerThread.run(HandlerThread.java:61)
04-12 11:48:55.799 4586-4648/com.google.firebase.samples.apps.mlkit E/TextNativeHandle: Error Loading module
    com.google.android.gms.dynamite.DynamiteModule$LoadingException: No acceptable module found. Local version is 0 and remote version is 0.
        at com.google.android.gms.dynamite.DynamiteModule.load(Unknown Source)
        at com.google.android.gms.internal.vision.zzm.zzq(Unknown Source)
        at com.google.android.gms.internal.vision.zzm.isOperational(Unknown Source)
        at com.google.android.gms.vision.text.TextRecognizer.isOperational(Unknown Source)
        at com.google.android.gms.internal.firebase_ml.zzqj.zzd(Unknown Source)
        at com.google.android.gms.internal.firebase_ml.zzqj.zza(Unknown Source)
        at com.google.android.gms.internal.firebase_ml.zzns.call(Unknown Source)
        at com.google.android.gms.internal.firebase_ml.zznn.zza(Unknown Source)
        at com.google.android.gms.internal.firebase_ml.zzno.run(Unknown Source)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at com.google.android.gms.internal.firebase_ml.zzi.dispatchMessage(Unknown Source)
        at android.os.Looper.loop(Looper.java:148)
        at android.os.HandlerThread.run(HandlerThread.java:61)
04-12 11:54:38.827 4586-4648/com.google.firebase.samples.apps.mlkit E/TextNativeHandle: Error Loading module
    com.google.android.gms.dynamite.DynamiteModule$LoadingException: No acceptable module found. Local version is 0 and remote version is 0.
        at com.google.android.gms.dynamite.DynamiteModule.load(Unknown Source)
        at com.google.android.gms.internal.vision.zzm.zzq(Unknown Source)
        at com.google.android.gms.internal.vision.zzak.<init>(Unknown Source)
        at com.google.android.gms.vision.text.TextRecognizer$Builder.build(Unknown Source)
        at com.google.android.gms.internal.firebase_ml.zzqj.zzlp(Unknown Source)
        at com.google.android.gms.internal.firebase_ml.zznx.zzf(Unknown Source)
        at com.google.android.gms.internal.firebase_ml.zzns.call(Unknown Source)
        at com.google.android.gms.internal.firebase_ml.zznn.zza(Unknown Source)
        at com.google.android.gms.internal.firebase_ml.zzno.run(Unknown Source)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at com.google.android.gms.internal.firebase_ml.zzi.dispatchMessage(Unknown Source)
        at android.os.Looper.loop(Looper.java:148)
        at android.os.HandlerThread.run(HandlerThread.java:61)
04-12 11:54:38.831 4586-4648/com.google.firebase.samples.apps.mlkit E/TextNativeHandle: Error Loading module
    com.google.android.gms.dynamite.DynamiteModule$LoadingException: No acceptable module found. Local version is 0 and remote version is 0.
        at com.google.android.gms.dynamite.DynamiteModule.load(Unknown Source)
        at com.google.android.gms.internal.vision.zzm.zzq(Unknown Source)
        at com.google.android.gms.internal.vision.zzm.isOperational(Unknown Source)
        at com.google.android.gms.vision.text.TextRecognizer.isOperational(Unknown Source)
        at com.google.android.gms.internal.firebase_ml.zzqj.zzd(Unknown Source)
        at com.google.android.gms.internal.firebase_ml.zzqj.zza(Unknown Source)
        at com.google.android.gms.internal.firebase_ml.zzns.call(Unknown Source)
        at com.google.android.gms.internal.firebase_ml.zznn.zza(Unknown Source)
        at com.google.android.gms.internal.firebase_ml.zzno.run(Unknown Source)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at com.google.android.gms.internal.firebase_ml.zzi.dispatchMessage(Unknown Source)
        at android.os.Looper.loop(Looper.java:148)
        at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by samtstern** [comment]
@Shekharb694 I found this information on their website:

> The M-Series Smart Glasses are not a CTS (Compatibility Test Suite) compliant device and does not support the Play Store or other Google Mobile Services (GMS) not covered by the Android Open Source license. 

So unfortunately I don't think that device can support MLKit today since it does not have Play services to download the module.

**Comment by GuanacoDevs** [comment]
@samtstern Been using MLKit for more than a year now. And so far never thought on checking for Google Play Services, that means that a check is a must before offering MLKit to the user?
Never thought on this before, because my mindset was on the app wouldn't be downloaded from the app store if it doesn't have Play Services, or is it that a manual install is not blocked.
The same way Android Studio won't let me run my app in an emulator that doesn't have Play Services.
Or is it safe to assume that the app is not installed from Google Play when no Play Services is available in the device and some installs may come from other sources, I have found my apps available(without my consent) in third party apps stores before I started to use Bundles.

**Comment by samtstern** [comment]
@GuanacoDevs if a device has the Google Play Store it has Google Play services and you should not have to think about it in that case.

Manual installs are not blocked. You can check for Google Play services with these calls:
https://developers.google.com/android/reference/com/google/android/gms/common/GoogleApiAvailability.html#isGooglePlayServicesAvailable(android.content.Context)

**Comment by coderau776** [comment]
private void detect()
    {
        FirebaseVisionImage image = FirebaseVisionImage.fromBitmap(imageBitmap);
        FirebaseVisionTextRecognizer detector = FirebaseVision.getInstance().getOnDeviceTextRecognizer();
        Task<FirebaseVisionText> result =
                detector.processImage(image)
                        .addOnSuccessListener(new OnSuccessListener<FirebaseVisionText>() {
                            @Override
                            public void onSuccess(FirebaseVisionText firebaseVisionText) {
                                // Task completed successfully
                                // ...
                                takeOutText(firebaseVisionText);
                            }
                        })
                        .addOnFailureListener(
                                new OnFailureListener() {
                                    @Override
                                    public void onFailure(@NonNull Exception e) {
                                        // Task failed with an exception
                                        // ...
                                        Toast.makeText(MainActivity.this,e.toString(),Toast.LENGTH_LONG).show();
                                    }
                                });
    }

Output 
Waiting for the text recognition model to be downloaded.Please wait
