### ISSUE TITLE
Kotlin NPE on MLKit sample

### ISSUE THREAD

**Issue by ytRino** [firebase/quickstart-android#874]
### Step 1: Describe your environment

  * Android device: Nexus 5X
  * Android OS version: 8.0.0
  * Google Play Services version: 17.1.22
  * Firebase/Play Services SDK version: firebase-ml-vision:20.0.0
  
### Step 2: Describe the problem:
App crashes on detection.

#### Steps to reproduce:

  1. Run MLKit Demo
  2. Select Kotlin version
  3. Select StillImageActivity
  4. Take Photo
  
#### Observed Results:
```
kotlin.KotlinNullPointerException
        at com.google.firebase.samples.apps.mlkit.kotlin.VisionProcessorBase$detectInVisionImage$1.onSuccess(VisionProcessorBase.kt:98)
        at com.google.android.gms.tasks.zzn.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```
  
#### Expected Results:

  * Result is overlayed
  
#### Relevant Code:

As stacktrace says,
https://github.com/firebase/quickstart-android/blob/master/mlkit/app/src/main/java/com/google/firebase/samples/apps/mlkit/kotlin/VisionProcessorBase.kt#L98
```
metadata!!,
```
crashes

**Comment by samtstern** [comment]
@ytRino thanks for reporting!
