### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by virat-shukla** [firebase/quickstart-android#97]
I am trying to build storage project. I have registered my project in firebase console, and downloaded google-services.json. After installing app on my Nexus5 phone, when i click on "SIGN IN" button, I get this error - 

Storage#MainActivity: signInAnonymously:FAILURE
                                                                                                    com.google.firebase.FirebaseException: An internal error has occured. [ OPERATION_NOT_ALLOWED ]
                                                                                                        at com.google.android.gms.internal.zzafg.zzes(Unknown Source)
                                                                                                        at com.google.android.gms.internal.zzafd$zzg.zza(Unknown Source)
                                                                                                        at com.google.android.gms.internal.zzafo.zzet(Unknown Source)
                                                                                                        at com.google.android.gms.internal.zzafo$zza.onFailure(Unknown Source)
                                                                                                        at com.google.android.gms.internal.zzafj$zza.onTransact(Unknown Source)
                                                                                                        at android.os.Binder.execTransact(Binder.java:453)

Please explain, how can i test this project on my phone. Do I have to build all projects, register all projects on firebase console, and download google-services.json for every project in order to work this project.

**Comment by samtstern** [comment]
Operation not allowed likely means you have not enabled Anonymous
Authentication in the Firebase Console.  Go to the console where you
registered the quick start project, go to the Auth tab, then go to Sign In
Methods and enable Anonymous.  That should fix it if you set everything
else up correctly.

**Comment by ahmgsk** [comment]
Might be U have not uploaded SHA1 certificate credential at Firebase console
