### ISSUE TITLE
NPE on FirebasePerfUrlConnection.instrument(FirebasePerfUrlConnection.java:13)

### ISSUE THREAD

**Issue by khalid64927** [firebase/quickstart-android#975]
### Step 1: Describe your environment

  * Android device: Galaxy J7,Grand Prime, S5
  * Android OS version:android 6,5,7,9
  * Google Play Services version: Not Known
  * Firebase/Play Services SDK version: Not Known
  
#### Steps to reproduce:

 Not able to reproduce on testing device,
  
#### Observed Results:

  * Caused by java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator 

Crashlytics Logs

Fatal Exception: java.lang.ExceptionInInitializerError
       at com.google.firebase.perf.internal.GaugeManager.<init>(GaugeManager.java:5)
       at com.google.firebase.perf.internal.GaugeManager.zzbf(GaugeManager.java:22)
       at com.google.android.gms.internal.firebase-perf.zzat.<init>(zzat.java:2)
       at com.google.android.gms.internal.firebase-perf.zzat.zza(zzat.java:1)
       at com.google.firebase.perf.network.FirebasePerfUrlConnection.instrument(FirebasePerfUrlConnection.java:13)
       at com.adobe.mobile.RequestHandler.requestConnect(RequestHandler.java:390)
       at com.adobe.mobile.RequestHandler.retrieveAnalyticsRequestData(RequestHandler.java:246)
       at com.adobe.mobile.AnalyticsWorker$1.run(AnalyticsWorker.java:304)
       at java.lang.Thread.run(Thread.java:818)

-----------------------------------

java.util.List.iterator()' on a null object reference
       at com.google.firebase.perf.internal.zzp.<init>(zzp.java:16)
       at com.google.firebase.perf.internal.zzp.<init>(zzp.java:6)
       at com.google.firebase.perf.internal.zzp.<clinit>(zzp.java:47)
       at com.google.firebase.perf.internal.GaugeManager.<init>(GaugeManager.java:5)
       at com.google.firebase.perf.internal.GaugeManager.zzbf(GaugeManager.java:22)
       at com.google.android.gms.internal.firebase-perf.zzat.<init>(zzat.java:2)
       at com.google.android.gms.internal.firebase-perf.zzat.zza(zzat.java:1)
       at com.google.firebase.perf.network.FirebasePerfUrlConnection.instrument(FirebasePerfUrlConnection.java:13)
       at com.adobe.mobile.RequestHandler.requestConnect(RequestHandler.java:390)
       at com.adobe.mobile.RequestHandler.retrieveAnalyticsRequestData(RequestHandler.java:246)
       at com.adobe.mobile.AnalyticsWorker$1.run(AnalyticsWorker.java:304)
       at java.lang.Thread.run(Thread.java:818)
  
#### Expected Results:

  * Should not crash
  
#### Relevant Code:

  ```
apply plugin: 'com.google.firebase.firebase-perf'
implementation "com.google.firebase:firebase-perf:16.2.2"
classpath "com.google.firebase:firebase-plugins:1.1.5"

  ```

**Comment by xncHung** [comment]
I also have the same issue
